import type { FrameworkGuide } from "./types";

export const GUIDES_PART4: Record<string, FrameworkGuide> = {
  /* ------------------------------------------------------------------ */
  "creative-testing": {
    overview: [
      "Creative testing and fatigue management is the discipline of treating ads as a portfolio of ideas that are tested, scaled and retired on purpose rather than by accident. In modern auction-based platforms, targeting is increasingly automated, so the creative itself has become the main lever an advertiser controls: the hook, the format, the message and the proof all decide who the algorithm finds and how cheaply.",
      "The framework has two halves. The first is structured testing: grouping creatives by concept (the underlying idea or angle) and format (video, static, carousel, UGC), then testing concepts against each other so that learning accumulates instead of being lost in hundreds of one-off variants. The second is fatigue detection: watching how performance decays as the same audience sees an ad repeatedly, so that refreshes happen before efficiency collapses rather than after.",
      "It answers a deceptively simple question: are we running out of effective creative? A rising CPA can be caused by auction pressure, tracking loss or seasonality, but very often it is simply that the winning ads are worn out and nothing ready is waiting to replace them.",
    ],
    whenToUse: [
      "CPA or cost per click is rising steadily on campaigns whose targeting and budgets have not changed.",
      "Click-through rate on top-spending ads is declining week on week while frequency keeps climbing.",
      "A handful of old ads carry most of the spend and new creatives rarely beat them.",
      "The team produces many variants but cannot say which messages or angles actually work.",
      "Scaling budget on a prospecting campaign quickly worsens efficiency.",
      "Brand, performance and agency teams disagree on what good creative looks like and there is no evidence to settle it.",
    ],
    howItWorks: [
      { step: "Tag every creative by concept and format", detail: "Build a simple taxonomy: concept or angle (for example price, social proof, problem-solution, founder story), format (static, short video, UGC, carousel), hook type and offer. Apply it consistently in ad names or a lookup sheet so performance can be rolled up by idea rather than by individual ad." },
      { step: "Establish the decay curve against frequency", detail: "For each major creative, plot CTR, conversion rate and CPA against cumulative frequency or weeks in market. Most ads show a plateau then a decline; the point where CPA rises meaningfully above its early level is the practical fatigue threshold for that audience size." },
      { step: "Run structured concept tests", detail: "Test a small number of genuinely different concepts at a time, each with two or three executions, in a controlled setup with equal budgets or a platform split test. Judge on a downstream metric such as cost per purchase or qualified lead, not just thumb-stop rate, and agree the minimum sample before launch." },
      { step: "Separate concept learning from execution learning", detail: "When a concept wins, iterate executions within it (new hooks, first three seconds, captions, creators). When a concept loses across several executions, retire the idea rather than endlessly re-cutting it. This keeps the learning library meaningful." },
      { step: "Set a refresh cadence matched to spend and audience size", detail: "Large budgets on narrow audiences fatigue fast; broad audiences with modest spend last longer. Use the observed decay curves to set how many new concepts and executions must enter the account each month so that a replacement is always ready before the leader tires." },
      { step: "Maintain a creative learning log", detail: "Record each test hypothesis, result and confidence in a shared log. Over a few quarters this becomes a brief for designers and agencies, showing which angles win for which audiences and which formats deserve production budget." },
    ],
    plainWords: "Imagine a café that tells the same joke on its chalkboard every day. The first week, people smile and walk in. By the fifth week, regulars do not even look at it, and the board stops pulling anyone through the door. Creative testing means trying several different chalkboard messages to find out which ideas really work, and noticing early when a favourite message has gone stale so a fresh one is ready to take its place.",
    examples: [
      {
        title: "E-commerce skincare brand on social video",
        situation: "A direct-to-consumer skincare brand saw blended CPA rise from 24 to 33 over eight weeks. Three ads made up 70% of spend, and their frequency in the core audience had climbed from 1.8 to 4.6.",
        analysis: "Plotting CPA by week in market showed each top ad held steady for about four weeks, then CPA rose roughly 10% per week. Tagging revealed all three shared the same before-and-after concept, so the account had no proven alternative angle. A concept test of ingredient education, dermatologist proof and customer routine videos was run with equal budgets.",
        outcome: "The customer routine concept beat the incumbent by about 18% on cost per purchase. The brand moved to launching two new concepts and six executions a month, and blended CPA settled back near 26 within six weeks (illustrative figures).",
      },
      {
        title: "Consumer bank credit card acquisition",
        situation: "A bank's display and social campaigns for a cashback card had flat CTR but falling application completion, and the agency kept producing colour and headline variants.",
        analysis: "Grouping two hundred variants into five concepts showed that 80% of variants were minor executions of one rewards-rate message. The only distinct concept tested, a no-annual-fee message, had been paused early on CTR alone despite a better approval rate.",
        outcome: "Re-testing on cost per approved account rather than CTR made the no-fee concept the winner by about 22%. Production effort shifted from variants to new concepts, and the learning log became part of the agency brief.",
      },
      {
        title: "SaaS project-management tool on paid social",
        situation: "A B2B SaaS company ran a single founder-story video for five months; trial sign-ups per week fell by a third while spend was constant.",
        analysis: "The audience was a narrow job-title segment of around 400,000 people, so frequency reached 7 within weeks. The decay curve showed cost per trial doubling after the first month.",
        outcome: "The team adopted a monthly refresh cadence with a template allowing quick re-cuts, and rotated three concepts (time saved, template library, peer proof). Cost per trial stabilised within roughly 15% of its launch level (illustrative).",
      },
    ],
    visuals: [
      {
        type: "line",
        title: "Creative fatigue: CPA rises as frequency builds",
        caption: "Notice that CPA holds steady for the first few weeks, then climbs as frequency passes about 3, which is the point to have a refresh ready.",
        xLabels: ["Wk 1", "Wk 2", "Wk 3", "Wk 4", "Wk 5", "Wk 6", "Wk 7"],
        yLabel: "Cost per acquisition",
        series: [
          { name: "Incumbent ad CPA", points: [24, 23, 24, 26, 29, 33, 37] },
          { name: "Frequency × 10", points: [12, 18, 24, 30, 36, 42, 47] },
        ],
      },
      {
        type: "bars",
        title: "Concept test: cost per purchase by concept",
        caption: "The customer routine concept wins clearly, so further executions should iterate within it rather than re-cutting the losing ideas.",
        unit: "cost per purchase",
        items: [
          { label: "Before-and-after (incumbent)", value: 31 },
          { label: "Ingredient education", value: 34 },
          { label: "Dermatologist proof", value: 29 },
          { label: "Customer routine", value: 25, highlight: true },
        ],
      },
    ],
    keyMetrics: [
      { name: "Hook rate", formula: "3-second video views ÷ impressions", meaning: "How well the opening stops the scroll; a leading indicator of creative interest." },
      { name: "Click-through rate (CTR)", formula: "Clicks ÷ impressions", meaning: "Whether the message earns action; a falling CTR at rising frequency is the classic fatigue signal." },
      { name: "Cost per acquisition by concept", formula: "Spend on concept ÷ conversions from concept", meaning: "The decision metric for concept tests, rolled up across executions." },
      { name: "Frequency", formula: "Impressions ÷ reach", meaning: "Average number of times each person has seen the ad; read alongside CPA to locate the fatigue threshold." },
      { name: "Creative win rate", formula: "New concepts beating control ÷ new concepts tested", meaning: "How productive the creative pipeline is; very low rates suggest briefs lack genuinely new ideas." },
    ],
    pitfalls: [
      "Testing dozens of tiny variants (button colour, one-word headline changes) and calling it creative strategy, so no real learning accumulates.",
      "Declaring winners on CTR or hook rate alone when the creative attracts cheap clicks that do not convert.",
      "Stopping tests before reaching an agreed sample, then over-reading noise.",
      "Waiting until CPA has already spiked before briefing new creative, leaving weeks of inefficient spend.",
      "Not tagging creatives consistently, so performance cannot be aggregated by concept or format later.",
    ],
    related: ["paid-efficiency", "experimentation", "frequency", "share-of-voice"],
  },

  /* ------------------------------------------------------------------ */
  mmm: {
    overview: [
      "Marketing mix modelling (MMM) is a statistical approach that estimates how much each marketing channel, along with non-marketing factors such as price, seasonality and the economy, contributed to sales or another outcome over time. It uses aggregated weekly or daily data rather than individual user journeys, which makes it robust to cookie loss and able to include offline media such as TV, radio, out-of-home and print.",
      "The method dates back to econometric work by consumer-goods companies in the 1960s and 1970s and has seen a revival as user-level tracking has become less reliable. Modern versions, including open-source Bayesian tools, model two key behaviours of advertising: adstock (the effect of an ad persists and decays over following weeks) and saturation (each extra unit of spend in a channel produces less incremental return than the last).",
      "MMM answers the question: how should budget be allocated across channels, including offline and brand? Its outputs are channel contribution, return on investment, marginal return curves and an optimised budget scenario, ideally calibrated against controlled experiments.",
    ],
    whenToUse: [
      "A significant share of budget goes to offline or upper-funnel media that click-based attribution cannot see.",
      "Platform-reported conversions add up to more than the business actually sold, and nobody trusts any single source.",
      "Leadership asks what would happen to sales if the budget were cut or increased by 20%.",
      "Signal loss from consent and privacy changes has weakened user-level attribution.",
      "Annual or quarterly budget planning needs an evidence base for the split between channels.",
      "You suspect some channels are saturated but cannot prove where diminishing returns begin.",
    ],
    howItWorks: [
      { step: "Assemble a clean weekly dataset", detail: "Collect at least two years of weekly outcomes (sales, revenue, sign-ups) alongside spend or impressions for every channel, prices and promotions, distribution, seasonality markers, holidays, competitor activity where available and macro factors. Consistency matters more than granularity: one row per week, one column per driver, with definitions fixed across the whole period." },
      { step: "Transform media for adstock and saturation", detail: "Apply an adstock transformation so that spend in one week carries over into later weeks with a decay rate, and a saturation curve so that response flattens at high spend. These parameters are estimated from the data, often with sensible priors, and they differ by channel: TV tends to decay slowly, search much faster." },
      { step: "Fit and validate the model", detail: "Estimate the model with regression, typically Bayesian, separating a baseline (sales that would happen without marketing) from incremental media contributions. Check fit on held-out weeks, look for implausible results such as negative effects of media, and test sensitivity to different priors and variable choices." },
      { step: "Calibrate with experiments", detail: "Where geo-lift tests, holdouts or conversion-lift studies exist, use their results to inform priors or to check the model's estimates. A model that disagrees badly with a well-run experiment needs investigation rather than blind trust." },
      { step: "Read response curves and marginal ROI", detail: "For each channel, plot the response curve and identify where current spend sits. Average ROI says what a channel has returned overall; marginal ROI says what the next unit of spend would return, which is what allocation decisions should be based on." },
      { step: "Optimise and scenario-plan the budget", detail: "Use the curves to simulate reallocations within a fixed budget and to test total budget changes. Apply business constraints such as minimum brand presence and contract commitments, then recommend a shift that equalises marginal returns across channels." },
      { step: "Refresh on a regular cadence", detail: "Re-run the model quarterly or semi-annually as new data arrives, and log every budget decision taken from it so the next version can test whether predicted changes actually happened." },
    ],
    plainWords: "Picture a lemonade stand that puts up posters, hands out flyers and pays a friend to shout on the corner, all at the same time. Sales go up, but which one helped? By looking at many weeks where each activity was done more or less, and also accounting for hot weather and holidays, you can work out roughly how much each one adds. You also find that a tenth poster on the same street does far less than the first one, so money might be better spent elsewhere.",
    examples: [
      {
        title: "Quick-service restaurant chain balancing TV and digital",
        situation: "A QSR chain spent 55% of its media budget on TV, 30% on paid social and 15% on search. Digital teams argued TV was wasteful because it showed no clicks.",
        analysis: "An MMM with three years of weekly data found TV contributed about 9% of sales with a long adstock, while paid social was close to saturation: its marginal ROI at current spend was around a third of its average ROI. Search was largely capturing demand created by TV.",
        outcome: "Moving 10% of the social budget into TV and regional out-of-home was projected to lift sales by around 2% at flat spend. A follow-up geo test confirmed a lift within the model's range (illustrative figures).",
      },
      {
        title: "Telecom operator after cookie loss",
        situation: "A mobile operator's last-click attribution showed paid search driving 60% of online sign-ups, but sign-ups had stayed flat despite a 25% increase in search spend.",
        analysis: "The MMM estimated that branded search was mostly harvesting existing demand, with a low incremental contribution, while radio and online video had unsaturated response curves. Price promotions explained a large share of week-to-week variation previously credited to media.",
        outcome: "The operator capped branded search bids, reinvested in video and radio, and ran a brand-search holdout in two regions that showed only a small sales drop, validating the model's direction.",
      },
      {
        title: "Online retailer planning peak season",
        situation: "An e-commerce retailer needed to decide whether a 20% budget increase for the holiday quarter would pay back.",
        analysis: "Scenario simulation using saturation curves showed the first 10% of extra budget delivered a marginal ROI above the target threshold, while the second 10% fell below it because affiliate and social would be heavily saturated.",
        outcome: "The retailer approved a 12% increase concentrated in under-saturated channels, avoiding spend that the model projected would not pay back.",
      },
    ],
    visuals: [
      {
        type: "line",
        title: "Saturation curves: incremental sales by spend level",
        caption: "Social flattens early while TV keeps rising, so the next unit of budget earns more in TV even if social's average return looks higher.",
        xLabels: ["0", "20k", "40k", "60k", "80k", "100k"],
        yLabel: "Incremental weekly sales (k)",
        series: [
          { name: "Paid social", points: [0, 48, 72, 84, 90, 93] },
          { name: "TV", points: [0, 30, 56, 78, 96, 110] },
          { name: "Search", points: [0, 40, 60, 70, 75, 78] },
        ],
      },
      {
        type: "waterfall",
        title: "Sales decomposition: baseline to total",
        caption: "Most sales are baseline demand; media channels add increments on top, which is why ROI must be judged on contribution, not on total sales.",
        unit: "k sales",
        items: [
          { label: "Baseline", value: 620 },
          { label: "Seasonality", value: 70 },
          { label: "Price promotions", value: 90 },
          { label: "TV", value: 85 },
          { label: "Paid social", value: 55 },
          { label: "Search", value: 40 },
          { label: "Total sales", value: 960, total: true },
        ],
      },
    ],
    keyMetrics: [
      { name: "Channel contribution", formula: "Modelled incremental sales from channel ÷ total sales", meaning: "Share of outcomes attributable to each channel after removing baseline and other drivers." },
      { name: "Average ROI", formula: "Incremental revenue from channel ÷ channel spend", meaning: "How well a channel has paid back overall across the period." },
      { name: "Marginal ROI", formula: "Change in incremental revenue ÷ change in spend at current level", meaning: "What the next unit of spend would return; the basis for reallocation." },
      { name: "Adstock half-life", meaning: "Weeks until a channel's effect falls to half; shows how long advertising keeps working after it airs." },
      { name: "Model fit (holdout MAPE)", formula: "Mean of |actual − predicted| ÷ actual on held-out weeks", meaning: "How accurately the model predicts weeks it was not trained on." },
    ],
    pitfalls: [
      "Using too little history or too little variation in spend, so the model cannot separate channel effects and falls back on priors.",
      "Allocating on average ROI instead of marginal ROI, which over-funds saturated channels.",
      "Omitting price, promotions or distribution changes, causing media to be credited with their effects.",
      "Treating a single model run as truth instead of validating with experiments and refreshing over time.",
      "Modelling at too aggregated a level (one total digital channel) to make any actionable decision.",
    ],
    related: ["attribution", "experimentation", "paid-efficiency", "share-of-voice"],
  },

  /* ------------------------------------------------------------------ */
  "signal-loss": {
    overview: [
      "A tracking and signal-loss audit checks whether the data marketers use to judge performance is still complete and accurate. Over recent years, browser restrictions on third-party cookies, mobile operating system privacy prompts, ad blockers and consent requirements have all reduced the share of conversions that ad platforms and analytics tools can observe. Broken or duplicated tags add further noise.",
      "The audit compares what the business actually recorded (orders, sign-ups, leads in the backend or CRM) with what each platform and analytics tool reports, then traces the gap to its causes: missing tags, consent refusals, browser blocking, attribution window changes or duplication. It then fixes what can be fixed, typically through server-side tagging and conversion APIs that send first-party events directly, and re-baselines KPIs for what cannot.",
      "The core question is: is the decline real or a measurement artefact? A sudden drop in reported ROAS might mean marketing is working worse, or simply that the platform is seeing fewer of the sales it still drives. Optimisation algorithms also learn from these signals, so lost data can genuinely harm performance as well as reporting.",
    ],
    whenToUse: [
      "Reported conversions or ROAS dropped sharply around a site release, consent banner change or platform update.",
      "Platform-reported conversions and backend orders diverge by a growing margin.",
      "A consent management platform was introduced or changed and analytics traffic fell overnight.",
      "Campaign learning phases reset frequently or bidding becomes unstable without obvious cause.",
      "Different tools report wildly different numbers for the same conversion event.",
      "A migration to a new analytics platform, tag manager or checkout is planned or recently completed.",
    ],
    howItWorks: [
      { step: "Reconcile platform against backend", detail: "Pull daily conversions from each ad platform and analytics tool next to the backend source of truth for the same definition (for example paid orders). Calculate the capture rate for each and plot it over time; a step change pinpoints when signal was lost, while a slow drift points to gradual factors such as browser updates." },
      { step: "Inventory and test every tag", detail: "List all tags and pixels, where they fire, what parameters they pass and whether they deduplicate. Test key journeys on different browsers and devices with consent accepted and refused, checking that purchase value, currency, order ID and hashed identifiers are passed correctly." },
      { step: "Audit consent and its effect", detail: "Measure consent acceptance rates by market, device and banner version, and confirm that tags honour choices correctly. Check whether consent-mode style modelling is enabled where lawful, since it can recover estimated conversions for users who decline cookies without tracking them individually." },
      { step: "Implement server-side tagging and conversion APIs", detail: "Send key events from your server or a server-side tag container directly to platforms, with consented first-party identifiers such as hashed email. Deduplicate against browser events with a shared event ID. This is more resilient to browser restrictions and ad blockers and improves the signal that bidding algorithms optimise on." },
      { step: "Re-baseline KPIs and reporting", detail: "Where loss cannot be recovered, adjust targets to the new capture rate rather than comparing to a pre-loss baseline. Use backend-based measures such as marketing efficiency ratio and incrementality tests as the anchor, and treat platform numbers as directional." },
      { step: "Monitor continuously", detail: "Set up a simple daily capture-rate dashboard with alerts when the ratio of platform to backend conversions moves beyond a tolerance. Most signal-loss incidents are discovered weeks late; automated reconciliation turns them into same-day fixes." },
    ],
    plainWords: "Think of a football coach who counts goals by watching from one corner of the pitch. When a big crowd stands up in front of them, they miss some goals and start believing the team is playing badly. A signal-loss audit is checking the official scoreboard against what the coach wrote down, finding where the view is blocked, and moving the coach to a better seat so the count is right again.",
    examples: [
      {
        title: "Online fashion retailer after a consent banner change",
        situation: "Reported social ROAS fell from 4.1 to 2.9 the week a new consent banner launched. The team was about to cut social budget by a third.",
        analysis: "Backend orders were flat week on week. Reconciliation showed the platform's capture rate of orders dropped from 78% to 55% exactly at launch, and testing revealed the purchase pixel only fired after an explicit opt-in that 40% of users declined.",
        outcome: "The retailer implemented a server-side conversion API with hashed email for consented customers and modelled conversions for the rest. Capture rose to about 72%, reported ROAS recovered to 3.8, and the budget cut was cancelled (illustrative figures).",
      },
      {
        title: "Airline with duplicated booking events",
        situation: "An airline's search platform showed more bookings than the reservation system recorded, inflating ROAS and justifying aggressive bids.",
        analysis: "The tag audit found the confirmation page fired the conversion twice on refresh and once more from a third-party payment redirect. No order ID was passed, so the platform could not deduplicate.",
        outcome: "Passing the booking reference as a transaction ID removed duplicates; reported bookings fell by 18% to match the backend, and bid targets were reset to realistic levels.",
      },
      {
        title: "Subscription app after a mobile privacy prompt change",
        situation: "A subscription app saw paid installs attributed to social drop by half while total installs in store analytics were stable.",
        analysis: "Most iOS users had declined app tracking, so user-level attribution was limited to aggregated, delayed postbacks. The decline was largely a visibility gap on one platform.",
        outcome: "The app adopted aggregated measurement frameworks for iOS, ran a geo holdout to estimate true incrementality, and re-based its iOS CPA targets on blended store data.",
      },
    ],
    visuals: [
      {
        type: "line",
        title: "Backend orders vs platform-reported conversions",
        caption: "Backend orders stay flat while platform conversions fall at the consent change, showing the drop is mostly lost signal rather than lost sales.",
        xLabels: ["Wk 1", "Wk 2", "Wk 3", "Wk 4", "Wk 5", "Wk 6"],
        yLabel: "Weekly orders",
        series: [
          { name: "Backend orders", points: [1000, 1010, 990, 1005, 1000, 1015] },
          { name: "Platform-reported", points: [780, 790, 550, 545, 690, 730] },
        ],
      },
      {
        type: "waterfall",
        title: "Where the conversions went",
        caption: "Consent refusals and browser restrictions explain most of the gap, which is why server-side events and modelling are the main fixes.",
        unit: "orders",
        items: [
          { label: "Backend orders", value: 1000 },
          { label: "Consent declined", value: -260 },
          { label: "Browser and ad blocking", value: -110 },
          { label: "Broken tag on mobile checkout", value: -60 },
          { label: "Duplicates", value: 20 },
          { label: "Platform-reported", value: 590, total: true },
        ],
      },
    ],
    keyMetrics: [
      { name: "Capture rate", formula: "Platform-reported conversions ÷ backend conversions", meaning: "Share of real conversions the platform sees; track daily per platform." },
      { name: "Consent rate", formula: "Users accepting marketing cookies ÷ users shown banner", meaning: "Upper bound on browser-based tracking coverage." },
      { name: "Event match quality", meaning: "Platform score or share of server events carrying a usable consented identifier; higher means better attribution and optimisation." },
      { name: "Deduplication rate", formula: "Events with matching browser and server IDs ÷ total server events", meaning: "Confirms server-side and browser events are not double-counted." },
      { name: "Marketing efficiency ratio (MER)", formula: "Total revenue ÷ total marketing spend", meaning: "A backend-based, tracking-independent anchor for overall efficiency." },
    ],
    pitfalls: [
      "Cutting budgets based on platform ROAS without checking backend outcomes first.",
      "Implementing server-side events without deduplication, which inflates conversions instead of recovering them.",
      "Sending identifiers or firing tags in ways that bypass user consent, creating legal and reputational risk.",
      "Comparing post-loss performance to pre-loss baselines without re-basing targets.",
      "Treating the audit as a one-off project rather than setting up ongoing reconciliation and alerts.",
    ],
    related: ["attribution", "data-governance", "mmm", "paid-efficiency"],
  },

  /* ------------------------------------------------------------------ */
  "seo-audit": {
    overview: [
      "A technical and content SEO audit is a structured diagnosis of why a website's organic search visibility is what it is, and what would improve it. It looks at three layers in order: whether search engines can crawl and index the right pages (technical health), whether those pages deserve to rank for what people search (content quality and intent fit), and whether the site has the authority and experience signals to compete.",
      "Audits are most often triggered by a change: a traffic drop after a site migration, a search engine core update, or a slow decline as competitors improve. The discipline lies in aligning the timing of the change with possible causes before jumping to fixes, because a crawl problem, an algorithm update and seasonal demand all look like falling traffic on a chart.",
      "It answers: why did organic visibility change, and what recovers it? The output is a prioritised list of fixes ranked by the traffic and revenue value of the pages they affect, not a long checklist of every minor warning a crawler tool can find.",
    ],
    whenToUse: [
      "Organic sessions or clicks fell noticeably and the cause is not obvious.",
      "A site migration, redesign, CMS change or domain move is planned or recently completed.",
      "A search engine confirmed a core or quality update around the time rankings moved.",
      "Many pages are excluded from the index or reported as crawled but not indexed.",
      "Competitors outrank you for commercially important queries despite similar offerings.",
      "Organic growth has plateaued and the team needs a prioritised work programme.",
    ],
    howItWorks: [
      { step: "Align the drop with updates, releases and demand", detail: "Plot daily clicks and impressions from Search Console alongside your release log, known algorithm updates and search demand trends. Segment by page type, device and country. A sharp drop on one template after a release suggests a technical cause; a gradual decline across informational pages around an update suggests content quality." },
      { step: "Check crawlability and indexation", detail: "Crawl the site and compare it with Search Console coverage. Look for blocked resources in robots rules, accidental noindex tags, wrong canonicals, redirect chains, orphan pages, broken internal links and sitemaps listing non-indexable URLs. Confirm important pages are reachable within a few clicks." },
      { step: "Review page experience and rendering", detail: "Check that content loads without depending on scripts the crawler cannot render, that mobile pages show the same content as desktop, and that loading and interaction performance are reasonable on real devices. Fix structured data errors on key templates." },
      { step: "Assess content quality and search intent fit", detail: "For each priority query group, compare your page with what currently ranks: is the format right (guide, list, product page, tool), does it answer the actual question, does it show first-hand expertise and up-to-date information? Identify thin, duplicated or cannibalising pages that compete with each other." },
      { step: "Evaluate authority and internal linking", detail: "Review backlink profile quality relative to competitors and, often more actionable, how internal links distribute authority to commercial pages. Hub pages linking to related pages with descriptive anchor text help search engines understand topical structure." },
      { step: "Prioritise fixes by traffic value", detail: "Estimate the value at stake for each issue: affected pages × their potential clicks × conversion value. Rank fixes by value against effort, tackle site-wide technical blockers first, and set a measurement plan to check recovery over the following weeks." },
    ],
    plainWords: "Imagine a library where your book is great but sits in a locked back room, has the wrong label on the spine, and the librarian cannot tell what it is about. Nobody will find it. An SEO audit checks that the door is open, the label is right, and the book really answers what people come in asking for, then fixes the problems that hide the most popular books first.",
    examples: [
      {
        title: "Retailer after a site migration",
        situation: "An online home-goods retailer moved to a new platform; organic revenue fell 35% within two weeks.",
        analysis: "Release-log alignment pointed to the migration. The crawl found 2,400 old category URLs redirecting to the homepage instead of their new equivalents, and new faceted filter pages were indexable, creating thousands of near-duplicate URLs.",
        outcome: "Mapping one-to-one redirects and canonicalising filters recovered most category rankings within about eight weeks; organic revenue returned to around 95% of pre-migration levels (illustrative figures).",
      },
      {
        title: "SaaS company hit by a core update",
        situation: "A SaaS company's blog lost 40% of clicks after a core update, while product pages were stable.",
        analysis: "Intent analysis showed many posts were generic, thin articles targeting broad terms, outranked by pages with original data and expert authors. Several posts cannibalised each other for the same queries.",
        outcome: "The team consolidated 120 posts into 35 deeper guides with named expert authors and original examples. Clicks recovered gradually and leads from organic rose above the pre-update baseline over two quarters.",
      },
      {
        title: "Bank with unindexed product pages",
        situation: "A retail bank's new savings product pages did not appear in search results weeks after launch.",
        analysis: "The pages rendered key content through a script the crawler could not execute and were missing from the sitemap and internal navigation.",
        outcome: "Server-side rendering and adding links from the savings hub got the pages indexed within days and ranking for product-name and rate queries.",
      },
    ],
    visuals: [
      {
        type: "bars",
        title: "Prioritising fixes by traffic value at stake",
        caption: "The redirect and indexation issues dwarf cosmetic warnings, so they go first regardless of how many minor errors a crawler reports.",
        unit: "monthly clicks at stake",
        items: [
          { label: "Broken migration redirects", value: 42000, highlight: true },
          { label: "Indexable duplicate filters", value: 18000 },
          { label: "Thin cannibalising posts", value: 11000 },
          { label: "Slow mobile templates", value: 6000 },
          { label: "Missing alt text", value: 800 },
        ],
      },
      {
        type: "line",
        title: "Organic clicks around a migration",
        caption: "Clicks drop at the migration and recover only after redirects are fixed, showing the cause was technical rather than demand.",
        xLabels: ["Wk -2", "Wk -1", "Launch", "Wk +1", "Wk +2", "Fix", "Wk +6", "Wk +8"],
        yLabel: "Weekly organic clicks (k)",
        series: [
          { name: "Organic clicks", points: [100, 102, 80, 66, 65, 70, 88, 95] },
        ],
      },
    ],
    keyMetrics: [
      { name: "Indexation rate", formula: "Indexed priority URLs ÷ priority URLs submitted", meaning: "Whether the pages that matter are actually in the index." },
      { name: "Organic click-through rate", formula: "Clicks ÷ impressions", meaning: "How compelling titles and snippets are at a given ranking." },
      { name: "Share of priority keywords in top 3", meaning: "Visibility on commercially important queries rather than vanity terms." },
      { name: "Organic conversion value", formula: "Organic sessions × conversion rate × average value", meaning: "Connects SEO work to revenue and justifies prioritisation." },
    ],
    pitfalls: [
      "Starting with a tool's list of hundreds of warnings instead of first establishing when and where traffic actually changed.",
      "Blaming an algorithm update for a drop that coincides with your own release.",
      "Producing more content to fix a technical indexing problem, or fixing technical issues when the real gap is intent and quality.",
      "Migrating without a full redirect map and pre and post crawl comparison.",
      "Measuring success on rankings for vanity terms rather than clicks and conversions on commercial pages.",
    ],
    related: ["content-strategy", "competitive", "ux-diagnosis", "funnel"],
  },

  /* ------------------------------------------------------------------ */
  "content-strategy": {
    overview: [
      "Content strategy with topic clusters is a way of planning what to publish so that each piece serves a real audience need at a specific stage of the buying journey, and together the pieces build recognised authority on a subject. The topic-cluster model, popularised in the content marketing community in the late 2010s, organises content around a central pillar page on a broad topic, linked to and from cluster pages that each cover a specific sub-question in depth.",
      "This structure helps people navigate from a general question to the detail they need, and helps search engines understand that a site covers a subject comprehensively. Beyond search, a strategy maps content to intents: awareness content explains problems, consideration content compares approaches and solutions, and decision content proves value with cases, pricing clarity and demonstrations.",
      "It answers: does our content earn attention and move people through the journey? Rather than counting posts or page views, it asks whether the content portfolio covers the questions buyers ask, and whether it measurably contributes to pipeline and conversions.",
    ],
    whenToUse: [
      "The blog publishes regularly but traffic and leads from content are flat.",
      "Content is organised by publishing date rather than by topic, and nobody knows what already exists.",
      "Sales teams say there is nothing useful to send prospects at the comparison or decision stage.",
      "Competitors appear consistently for a whole topic area while you appear for scattered terms.",
      "Content performance is judged on page views alone, with no link to pipeline.",
      "Several pages compete for the same query, splitting rankings and confusing readers.",
    ],
    howItWorks: [
      { step: "Audit existing content by stage and intent", detail: "Export every content URL with traffic, engagement, conversions and target topic. Classify each by journey stage (awareness, consideration, decision, retention) and search intent (informational, commercial, transactional). Mark each piece to keep, update, merge or remove." },
      { step: "Research demand and find gaps", detail: "Use keyword research, sales call notes, support tickets and community questions to list the questions buyers actually ask on each core topic. Compare against the audit to find unanswered questions and stages with little coverage, often the commercial comparison stage." },
      { step: "Design pillars and clusters", detail: "For each core topic, define one pillar page that gives a complete overview and links to cluster pages answering specific sub-questions. Each cluster page links back to the pillar and to sibling pages where useful. Assign one primary intent per page to avoid cannibalisation." },
      { step: "Plan production with differentiation", detail: "Prioritise gaps by business value and feasibility. For each brief, define what makes the piece better than what already ranks: original data, expert input, worked examples, tools or templates. Repurpose the strongest pieces into email, social and sales enablement." },
      { step: "Connect content to conversion paths", detail: "Add relevant next steps on each page matched to its stage: a related guide for awareness readers, a comparison or calculator for consideration, a demo or trial for decision. Track micro-conversions such as newsletter sign-ups and resource downloads." },
      { step: "Measure assisted conversions and refresh", detail: "Report content's contribution through assisted conversions, content-influenced pipeline and engagement depth, not just last-click. Review clusters quarterly, refreshing pages that decay and expanding clusters that convert." },
    ],
    plainWords: "Think of a well-run bookshop. Instead of piling books by the date they arrived, it has a cooking section with a big general cookbook at the front and smaller books on bread, curries and desserts around it, each pointing to the others. Customers find what they need, and people start thinking of the shop as the place for cooking books. Content strategy organises your articles the same way so readers find their next step and trust you on the subject.",
    examples: [
      {
        title: "B2B payroll SaaS building a cluster",
        situation: "A payroll software company had 300 blog posts, mostly news and generic HR tips, generating traffic but few demo requests.",
        analysis: "The audit found 70% of posts were awareness-stage with no clear next step and almost nothing addressed payroll compliance comparisons, which sales said was the top buying question. A cluster on payroll compliance was planned: one pillar and 14 cluster pages, plus a comparison guide and a calculator.",
        outcome: "Over two quarters, the cluster drew a smaller share of total traffic but generated around 40% of content-assisted demo requests, and 90 low-value posts were merged or removed (illustrative figures).",
      },
      {
        title: "Telecom provider's help and buying content",
        situation: "A broadband provider's site ranked for support queries but rarely for plan comparison searches.",
        analysis: "Intent mapping showed decision-stage questions such as speed needed for streaming or gaming were unanswered. The existing plan page tried to rank for everything and ranked for nothing specific.",
        outcome: "A pillar on choosing broadband with clusters on speed, gaming, working from home and switching providers lifted organic sales enquiries and gave call-centre staff links to send customers.",
      },
      {
        title: "Online retailer of outdoor gear",
        situation: "A retailer published seasonal gift guides that spiked and vanished each year.",
        analysis: "The guides were not linked to evergreen buying guides on tents, boots and layering, so authority was not accumulating between seasons.",
        outcome: "Building evergreen clusters and linking seasonal guides into them produced steadier year-round organic revenue and higher rankings during peak.",
      },
    ],
    visuals: [
      {
        type: "bars",
        title: "Content inventory by journey stage",
        caption: "Most content sits at awareness while consideration and decision are thin, which is where buyers need help and where the gaps should be filled first.",
        unit: "pages",
        items: [
          { label: "Awareness", value: 210 },
          { label: "Consideration", value: 45, highlight: true },
          { label: "Decision", value: 15, highlight: true },
          { label: "Retention", value: 30 },
        ],
      },
      {
        type: "funnel",
        title: "Content-assisted journey for one cluster",
        caption: "Each step loses readers, but linking pages to the next stage keeps more of them moving towards a demo.",
        stages: [
          { label: "Cluster page visits", value: 20000 },
          { label: "Visits to pillar or comparison", value: 5000 },
          { label: "Resource downloads", value: 900 },
          { label: "Demo requests", value: 180 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Topic coverage", formula: "Priority questions answered ÷ priority questions identified", meaning: "How completely the content answers what buyers ask on a topic." },
      { name: "Content-assisted conversions", meaning: "Conversions where a content page appeared in the journey before the conversion, not only last-click." },
      { name: "Engaged time and scroll depth", meaning: "Whether readers actually consume the content rather than bounce." },
      { name: "Next-step click rate", formula: "Clicks on in-content next steps ÷ page views", meaning: "How well content moves readers forward through the journey." },
      { name: "Content decay rate", meaning: "Share of pages losing more than a set percentage of traffic over a period; flags refresh candidates." },
    ],
    pitfalls: [
      "Publishing to a volume target with no map of topics, stages or intents.",
      "Writing generic content that restates what already ranks without original insight.",
      "Judging content solely on last-click conversions, undervaluing awareness and consideration pieces.",
      "Creating multiple pages for the same intent, so they compete with each other.",
      "Never updating or pruning old content, letting the library decay.",
    ],
    related: ["seo-audit", "jtbd", "b2b-funnel", "brand-funnel"],
  },

  /* ------------------------------------------------------------------ */
  "nps-drivers": {
    overview: [
      "NPS and voice-of-customer (VoC) driver analysis connects what customers say about their experience to how they behave. Net Promoter Score, introduced by Fred Reichheld in 2003, asks how likely someone is to recommend a company on a 0–10 scale; promoters score 9–10, passives 7–8 and detractors 0–6, and NPS is the percentage of promoters minus the percentage of detractors.",
      "On its own, a score says little about what to fix. Driver analysis adds two things: theming the open-text comments (verbatims) and operational data to find which experience issues come up, and statistically estimating which of those issues actually move the score and, more importantly, which link to churn, spend or complaints in behavioural data.",
      "It answers: which experience issues drive detractors and churn? The result is a short, prioritised list of fixable drivers with clear owners, rather than a dashboard of scores that everyone watches and nobody acts on.",
    ],
    whenToUse: [
      "NPS or CSAT is tracked but nobody can say what would raise it.",
      "Churn is rising and the team wants to know which experience failures cause it.",
      "Thousands of verbatim comments sit unread in a survey tool.",
      "Different departments each claim their area is the top customer pain point.",
      "Review ratings are falling on public sites and the reasons are unclear.",
      "Leadership wants to prioritise service or product investment by customer impact.",
    ],
    howItWorks: [
      { step: "Collect and link feedback to customer records", detail: "Gather survey responses with their verbatims and link them to customer IDs so that each response sits next to behaviour: tenure, product, spend, support contacts and whether the customer later churned. Without the link, analysis stops at opinions." },
      { step: "Theme the verbatims", detail: "Build a codeframe of experience themes (for example delivery delays, billing errors, app reliability, staff helpfulness) from a sample, then classify all comments, manually or with text analytics, and check accuracy on a validation sample. Record sentiment per theme as well as presence." },
      { step: "Run key-driver analysis", detail: "Estimate how strongly each theme or rated attribute relates to the likelihood-to-recommend score, using regression or relative-importance methods. Plot importance against current performance to separate critical weaknesses from strengths and low-priority issues." },
      { step: "Link drivers to churn and value", detail: "Compare churn rates, spend and contact volumes for customers who mentioned each driver versus those who did not, controlling for segment where possible. A driver that barely moves NPS but doubles churn deserves more attention than its score impact suggests." },
      { step: "Size and prioritise", detail: "For each driver, estimate customers affected × change in churn or spend × customer value to get revenue at risk. Combine with cost and feasibility of fixes to rank the shortlist." },
      { step: "Close the loop with owners", detail: "Assign each driver to an accountable team with a target, contact detractors where appropriate to resolve individual issues, and re-measure after fixes. Share back to customers what changed, which itself improves perception." },
    ],
    plainWords: "Think of a neighbourhood pizza shop that asks every customer for a score out of ten and a comment. The score alone just says some people are unhappy. Reading all the comments shows that cold pizza and late delivery come up a lot, and checking the order history shows that people who complained about cold pizza stopped ordering. Driver analysis is finding which complaint actually loses customers, so the shop fixes the oven bag first rather than repainting the sign.",
    examples: [
      {
        title: "Telecom operator reducing churn",
        situation: "A mobile operator had an NPS of 12 and monthly churn of 1.8%. Network coverage was assumed to be the main problem.",
        analysis: "Theming 40,000 verbatims and linking to churn showed coverage was mentioned most often, but customers citing unexpected bill charges churned at 3.5 times the base rate. Key-driver analysis placed billing clarity as high importance with low performance.",
        outcome: "Clearer bill explanations and proactive alerts before roaming charges cut billing-related contacts by about a quarter and churn among affected customers by roughly a third over six months (illustrative figures).",
      },
      {
        title: "Airline improving recommendation scores",
        situation: "An airline's NPS fell eight points in a year; the board suspected seat comfort after a fleet change.",
        analysis: "Driver analysis found seat comfort had modest importance, while disruption handling (rebooking and communication during delays) had the highest importance and the steepest decline, and was linked to lower repeat booking.",
        outcome: "Investment shifted to automated rebooking and proactive delay messages. NPS among disrupted passengers improved markedly while overall NPS recovered most of the lost ground.",
      },
      {
        title: "E-commerce marketplace returns experience",
        situation: "A marketplace's reviews were steady, but repeat purchase among first-time buyers was falling.",
        analysis: "Linking post-purchase survey themes to repeat behaviour showed that first-time buyers who mentioned difficult returns repurchased at half the rate of others.",
        outcome: "A simplified returns flow with prepaid labels became the top fix, owned by operations with a repeat-rate target.",
      },
    ],
    visuals: [
      {
        type: "matrix",
        title: "Driver importance vs performance",
        caption: "Billing clarity and disruption handling sit in the fix-first quadrant: they matter a lot and currently perform poorly.",
        xLabel: "Current performance",
        yLabel: "Impact on recommendation",
        quadrants: ["Fix first", "Protect strengths", "Monitor", "Maintain, do not over-invest"],
        points: [
          { label: "Billing clarity", x: 22, y: 82 },
          { label: "Disruption handling", x: 30, y: 74 },
          { label: "Staff helpfulness", x: 78, y: 70 },
          { label: "Network coverage", x: 60, y: 45 },
          { label: "App design", x: 35, y: 25 },
          { label: "Store ambience", x: 80, y: 15 },
        ],
      },
      {
        type: "bars",
        title: "Annual churn rate by driver mentioned",
        caption: "Customers mentioning billing issues churn far more than others, even though billing is not the most frequently mentioned theme.",
        unit: "% churn",
        items: [
          { label: "No issue mentioned", value: 14 },
          { label: "Network coverage", value: 22 },
          { label: "Customer service wait", value: 27 },
          { label: "Unexpected bill charges", value: 49, highlight: true },
        ],
      },
    ],
    keyMetrics: [
      { name: "Net Promoter Score", formula: "% promoters (9–10) − % detractors (0–6)", meaning: "Overall advocacy level, ranging from −100 to +100." },
      { name: "Driver importance", meaning: "Statistical weight of each theme or attribute in explaining the likelihood-to-recommend score." },
      { name: "Churn lift by driver", formula: "Churn rate of customers citing driver ÷ churn rate of others", meaning: "How strongly an experience issue predicts customers leaving." },
      { name: "Revenue at risk", formula: "Customers affected × churn lift effect × average customer value", meaning: "Sizes each driver in money to prioritise fixes." },
      { name: "Closed-loop rate", formula: "Detractors followed up within target time ÷ total detractors", meaning: "Whether feedback triggers action at individual level." },
    ],
    pitfalls: [
      "Ranking issues by how often they are mentioned rather than by their effect on loyalty and churn.",
      "Analysing survey scores without linking to behavioural data, so impact on revenue stays unknown.",
      "Tying staff bonuses to NPS, which encourages score-begging and gaming.",
      "Reading small changes in NPS as meaningful without considering sample size and margin of error.",
      "Producing insight reports without assigning owners, targets and follow-up measurement.",
    ],
    related: ["churn", "loyalty-tiering", "referral-loop", "ux-diagnosis"],
  },

  /* ------------------------------------------------------------------ */
  "referral-loop": {
    overview: [
      "Referral and viral loop design is the practice of turning existing customers into a repeatable acquisition channel. A loop works when each new customer, through invitations, sharing or simply using the product with others, brings in further customers, who in turn bring in more. Well-known examples include double-sided referral rewards, where both the referrer and the friend receive something, and products that are naturally more useful when others join.",
      "The key measure is the viral coefficient, often called k-factor: the average number of new customers each customer brings in, calculated as invitations sent per customer multiplied by the conversion rate of those invitations. Below 1, referrals amplify other acquisition channels; above 1, growth becomes self-sustaining for as long as it lasts. Cycle time, how long one turn of the loop takes, matters as much as k.",
      "It answers: can satisfied customers become a scalable acquisition channel? Designing a loop means finding the moments when customers are happiest, giving them a reason and an easy way to share, and making sure the friend has a good reason to accept, while preventing fraud and abuse.",
    ],
    whenToUse: [
      "Customers are satisfied and recommend you informally, but there is no structured way to capture this.",
      "Paid acquisition costs are rising and a cheaper, higher-quality source is needed.",
      "An existing referral programme has low participation or its rewards are being abused.",
      "The product becomes more valuable when more people use it together.",
      "Referred customers appear to retain or spend more than paid-acquired ones.",
      "A launch into a new market needs trust that word of mouth can provide better than ads.",
    ],
    howItWorks: [
      { step: "Identify promoter moments", detail: "Find the points where customers feel the most value: right after a successful delivery, a first saving, a milestone reached, a high NPS response. Prompts at these moments get far more shares than a generic invite link buried in settings." },
      { step: "Design a two-sided incentive", detail: "Give the friend a reason to act (a discount, extra credit, a free month) and the referrer a reward that fits the brand and margin. Test monetary versus status or product-based rewards. Make sure the reward value is justified by referred customer lifetime value, not just first purchase." },
      { step: "Reduce sharing and redemption friction", detail: "Pre-write messages, support the channels people actually use (messaging apps, email, links), and make the friend's landing page explain the offer instantly with the referrer's name for trust. Apply the reward automatically rather than requiring codes where possible." },
      { step: "Instrument the full loop", detail: "Track each step: customers who see the prompt, who share, invitations sent, invitations opened, friends who sign up, friends who become active or paying, and the time between steps. Attribute rewards only on a qualifying action such as first paid order." },
      { step: "Measure k-factor, cycle time and quality", detail: "Calculate k as invitations per customer × invitation conversion rate, measure cycle time, and compare retention and value of referred versus other customers. A loop with modest k but fast cycle time can still compound meaningfully." },
      { step: "Control fraud and iterate", detail: "Watch for self-referrals, duplicate accounts, coupon sites and reward farming using device, payment and address checks plus caps. Run experiments on prompt timing, message and incentive, changing one variable at a time." },
    ],
    plainWords: "Think of a lemonade stand where every happy customer gets a card saying: give this to a friend and you both get a free cup next time. If each customer brings in, on average, half a new customer, the stand grows faster than from signs alone. If each brings in more than one, the line keeps growing by itself. The trick is handing out the card when people are smiling, making it easy to pass on, and stopping anyone from giving cards to themselves.",
    examples: [
      {
        title: "Neobank double-sided referral",
        situation: "A digital bank offered referrers a small cash reward for each friend who opened an account; k-factor was around 0.08.",
        analysis: "Funnel analysis showed only 6% of customers ever saw the referral screen, and friends dropped off because the reward required a minimum deposit explained only in small print. Customers who had just received their first salary deposit were twice as likely to share.",
        outcome: "Moving the prompt to the first-salary moment, adding a reward for the friend and showing the condition upfront raised k to roughly 0.21, with referred customers retaining better than paid-acquired ones (illustrative figures).",
      },
      {
        title: "Meal-kit e-commerce referral abuse",
        situation: "A meal-kit company's referral programme drove high sign-up volume but low second-order rates.",
        analysis: "A large share of referrals came from a few accounts posting codes on coupon sites, and many friends cancelled after the discounted first box. The reward paid out on sign-up rather than on retained customers.",
        outcome: "Paying the referrer after the friend's second box, capping rewards per account and adding device checks cut referral volume by a third but improved referred-customer retention and net payback.",
      },
      {
        title: "Collaboration SaaS built-in loop",
        situation: "A document collaboration tool relied on paid search for new teams.",
        analysis: "Each shared document exposed non-users to the product, but the viewer page offered no clear path to sign up. Invited collaborators converted at only 4%.",
        outcome: "Adding a lightweight sign-up on shared documents and a prompt to invite teammates after first collaboration lifted invited-viewer conversion to about 9%, making product-led sharing a top acquisition source.",
      },
    ],
    visuals: [
      {
        type: "cycle",
        title: "The referral loop",
        caption: "Each step feeds the next; improving any single step raises the number of new customers each turn of the loop produces.",
        steps: ["Customer gets value", "Prompt at promoter moment", "Customer shares invite", "Friend sees clear offer", "Friend signs up and activates", "Friend becomes a customer who gets value"],
      },
      {
        type: "funnel",
        title: "Referral funnel per 1,000 active customers",
        caption: "Only a small share of customers share, so prompt reach and timing are often the biggest levers on k-factor.",
        stages: [
          { label: "Active customers", value: 1000 },
          { label: "Saw referral prompt", value: 400 },
          { label: "Shared at least once", value: 120 },
          { label: "Invites opened", value: 600 },
          { label: "Friends signed up", value: 150 },
          { label: "Friends activated", value: 100 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Viral coefficient (k-factor)", formula: "Invites sent per customer × invite-to-customer conversion rate", meaning: "New customers generated by each existing customer per loop cycle." },
      { name: "Viral cycle time", meaning: "Average time from a customer joining to their invitees joining; shorter cycles compound faster." },
      { name: "Share rate", formula: "Customers who share ÷ customers shown the prompt", meaning: "How compelling the prompt and incentive are." },
      { name: "Referred customer LTV ratio", formula: "LTV of referred customers ÷ LTV of other customers", meaning: "Whether referrals bring higher-quality customers." },
      { name: "Cost per referred customer", formula: "Total rewards and programme costs ÷ qualified referred customers", meaning: "Compared with CAC from other channels to judge efficiency." },
    ],
    pitfalls: [
      "Paying rewards on sign-up rather than a qualifying action, inviting fraud and low-quality customers.",
      "Hiding the referral option in settings instead of placing it at moments of delight.",
      "Offering a reward only to the referrer, giving the friend no reason to act.",
      "Expecting a referral programme to fix a product people are not happy with.",
      "Ignoring cycle time and quality, focusing only on raw referral volume.",
    ],
    related: ["nps-drivers", "aarrr", "cac", "app-growth"],
  },

  /* ------------------------------------------------------------------ */
  "app-growth": {
    overview: [
      "The app growth funnel traces a mobile user's path from first seeing an app in the store to using it as a habit: store impression, store page view, install, first open, onboarding completion, permission grants (such as notifications), first key action, and retention on day 1, day 7 and day 30. App store optimisation (ASO) covers the top of this funnel; onboarding and engagement design cover the rest.",
      "Apps face distinct challenges compared with websites: users must commit to a download, operating systems control permission prompts and tracking, uninstalls are one tap away, and store ratings strongly influence conversion. Typical app retention curves fall steeply in the first days and then flatten, so the shape of the early curve largely decides long-term user numbers.",
      "It answers: where does the app lose users from store page to habit? By measuring each step and comparing cohorts, teams find whether the bottleneck is store conversion, onboarding friction, permission design or a weak reason to return.",
    ],
    whenToUse: [
      "Installs are growing but active users are flat because new users drop off quickly.",
      "Store page conversion is low or falling, or ratings have dropped.",
      "Push notification opt-in is low, limiting the ability to re-engage users.",
      "Day-1 retention is weak and onboarding has many screens before value.",
      "Paid install costs are rising and the team needs more value from each install.",
      "Uninstalls spike after a release or after certain notification campaigns.",
    ],
    howItWorks: [
      { step: "Benchmark and improve store conversion", detail: "Measure store page conversion (installs ÷ page views) by traffic source and country. Test icon, screenshots, preview video, title and subtitle using store experiments, ensuring the first two screenshots show the core value. Respond to reviews and fix issues that drive low ratings." },
      { step: "Map onboarding drop-off screen by screen", detail: "Instrument every onboarding step and plot the funnel from first open to the first meaningful action. Remove or defer steps that are not needed to experience value, such as long sign-up forms; let users explore before creating an account where possible." },
      { step: "Design permission prompts around value", detail: "Ask for notifications, location or tracking only when the user understands the benefit, using a pre-prompt screen explaining why. A system prompt can usually be shown only once, so a poorly timed request permanently lowers opt-in." },
      { step: "Reach the aha moment fast", detail: "Identify the early action most correlated with long-term retention, for example completing a first workout, saving a first item or making a first transfer. Redesign the first session so most new users reach it, and measure time to that action." },
      { step: "Build D1, D7 and D30 habit loops", detail: "Plot retention curves by install cohort and source. Use relevant triggers (reminders, streaks, content updates, saved progress) aligned to the natural usage frequency of the app. Be careful with notification volume, as excess drives uninstalls and opt-outs." },
      { step: "Attribute and compare by source", detail: "Compare retention and value by acquisition source and campaign, not just install cost. Under mobile privacy rules, use aggregated attribution and store analytics; judge channels on cost per retained or paying user." },
    ],
    plainWords: "Imagine opening a new gym. First people have to notice the poster, then walk in, then sign up, then actually come back the next week. If the sign-up form is ten pages long or nobody shows them how to use the machines, most never return. The app growth funnel looks at each of those steps, finds where most people give up, and fixes that step first so more of them turn into regulars.",
    examples: [
      {
        title: "Fitness app improving early retention",
        situation: "A fitness app had a store conversion rate of 32% but day-7 retention of only 11%.",
        analysis: "Onboarding had nine screens and asked for an account, notifications and health data permissions before showing any workout. Users who completed a first workout on day 0 had more than three times the day-7 retention of those who did not.",
        outcome: "Cutting onboarding to three screens, letting users start a workout immediately and asking for notifications after the first workout raised first-session workout completion and lifted day-7 retention to about 17% (illustrative figures).",
      },
      {
        title: "Retail banking app push opt-in",
        situation: "A bank's app had a notification opt-in rate of 38%, limiting fraud alerts and engagement messages.",
        analysis: "The system permission prompt appeared on first launch with no explanation. Opt-in among users shown a pre-prompt explaining instant spending alerts in a test was much higher.",
        outcome: "Showing the prompt after the first login with a clear security-alert explanation raised opt-in to around 62%, and alert-driven app opens increased.",
      },
      {
        title: "Food delivery app store page",
        situation: "A food delivery app's store conversion lagged in a new market.",
        analysis: "Screenshots showed restaurants unknown locally, and the rating had dropped after a payment bug. Review analysis confirmed payment failures as the main complaint.",
        outcome: "Localised screenshots featuring popular local restaurants, a fix for the payment bug and responses to recent reviews raised store conversion and recovered the rating.",
      },
    ],
    visuals: [
      {
        type: "funnel",
        title: "From store page to day-7 habit",
        caption: "The steepest losses happen between first open and the first key action, so onboarding is the priority before buying more installs.",
        stages: [
          { label: "Store page views", value: 10000 },
          { label: "Installs", value: 3200 },
          { label: "First opens", value: 2900 },
          { label: "Onboarding completed", value: 1700 },
          { label: "First key action", value: 1100 },
          { label: "Active on day 7", value: 450 },
        ],
      },
      {
        type: "line",
        title: "Retention curves before and after onboarding redesign",
        caption: "The redesigned cohort loses fewer users in the first days and the curve flattens at a higher level, which compounds into more long-term users.",
        xLabels: ["D0", "D1", "D3", "D7", "D14", "D30"],
        yLabel: "% of install cohort active",
        series: [
          { name: "Old onboarding", points: [100, 28, 17, 11, 8, 6] },
          { name: "New onboarding", points: [100, 36, 24, 17, 13, 10] },
        ],
      },
    ],
    keyMetrics: [
      { name: "Store conversion rate", formula: "Installs ÷ store page views", meaning: "How persuasive the store listing is." },
      { name: "Onboarding completion", formula: "Users completing onboarding ÷ first opens", meaning: "How much friction stands between install and use." },
      { name: "Push opt-in rate", formula: "Users granting notification permission ÷ users prompted", meaning: "Reach of the main re-engagement channel." },
      { name: "D1 / D7 / D30 retention", formula: "Users active on day N ÷ users installed on day 0", meaning: "Shape of the retention curve and habit formation." },
      { name: "Cost per retained user", formula: "Acquisition spend ÷ users active on day 30", meaning: "Judges acquisition sources on quality rather than install volume." },
    ],
    pitfalls: [
      "Scaling paid installs before fixing onboarding and early retention, buying users who leave.",
      "Requesting all permissions on first launch with no explanation.",
      "Judging campaigns on cost per install instead of cost per retained or paying user.",
      "Sending frequent generic notifications that drive opt-outs and uninstalls.",
      "Ignoring store ratings and reviews, which directly affect store conversion.",
    ],
    related: ["activation", "cohort", "engagement-decay", "referral-loop"],
  },

  /* ------------------------------------------------------------------ */
  "data-governance": {
    overview: [
      "Data quality, identity and consent readiness is an assessment of whether a company's customer data is fit to power targeting, personalisation and measurement. Many marketing initiatives fail not because the idea is wrong but because the data underneath is incomplete, duplicated, out of date, unlinked across systems or collected without the consent needed to use it.",
      "The framework examines four dimensions. Identity: can records from the website, app, CRM, point of sale and service systems be matched to the same person, and how often? Quality: are key fields complete, valid, consistent and fresh? Latency: does data arrive fast enough for the use case, such as within minutes for cart abandonment? Consent: is permission recorded per purpose and channel, in line with regulations such as GDPR in Europe or the DPDP Act in India, and is it respected downstream?",
      "It answers: is our data fit to power targeting, personalisation and measurement? The output is a clear picture of gaps and a defined minimum viable data foundation, the smallest set of fixes needed to launch the priority use cases.",
    ],
    whenToUse: [
      "A customer data platform or CRM investment is planned or underperforming.",
      "Personalisation or audience targeting delivers weak results and data quality is suspected.",
      "The same customer appears as several records across systems, leading to duplicate or contradictory messages.",
      "Audience sizes in activation tools are much smaller than the customer base.",
      "A privacy regulation change or audit requires proof of lawful consent and data use.",
      "Measurement disagrees across tools because customer and event data are inconsistent.",
    ],
    howItWorks: [
      { step: "Inventory sources and flows", detail: "List every system that holds customer or event data: website and app analytics, CRM, e-commerce, point of sale, loyalty, service, email and ad platforms. For each, note the identifiers it holds, how often it syncs, who owns it and where data flows next." },
      { step: "Measure identity match rates", detail: "Determine which identifiers link systems (customer ID, email, phone, device ID, loyalty number) and calculate how many records in each source can be matched to a single customer profile. Low match rates between online and offline data are common and limit omnichannel use cases." },
      { step: "Assess data quality dimensions", detail: "For the fields that priority use cases need, measure completeness, validity (correct format), consistency across systems, uniqueness (duplicates) and freshness. Score each and identify root causes such as optional form fields, free-text entry or batch jobs that run weekly." },
      { step: "Assess consent coverage and enforcement", detail: "Measure the share of profiles with valid, purpose-specific consent for each channel and use (email, SMS, personalised ads, analytics), check that consent records carry timestamps and sources, and test that downstream tools actually suppress non-consented profiles." },
      { step: "Map gaps against priority use cases", detail: "For each planned use case, list the data it requires, the required latency and the consent basis, then mark where current data falls short. This turns a generic data audit into a specific readiness verdict per use case." },
      { step: "Define the minimum viable data foundation", detail: "Choose the smallest set of fixes that unlocks the highest-value use cases, for example capturing email at checkout, a nightly identity merge and a central consent record, with owners and data quality targets. Monitor these metrics continuously rather than auditing once." },
    ],
    plainWords: "Imagine a football club trying to send each fan a personal birthday message. If some fans are written down twice with different spellings, some have no birthday on file, some details are years old, and some never said they wanted messages at all, the plan goes wrong. This framework checks how tidy and complete the club's list is, whether it knows which records are the same person, and whether it has permission, then fixes just enough to make the most valuable ideas work.",
    examples: [
      {
        title: "Retailer preparing for omnichannel personalisation",
        situation: "A fashion retailer bought a customer data platform to personalise emails using in-store and online purchases, but audiences were small and recommendations poor.",
        analysis: "Only 31% of store transactions were linked to a known customer because staff rarely captured email or loyalty number at the till. Online profiles had 12% duplicates from guest checkouts.",
        outcome: "Digital receipts offered at the till and guest-to-account merging raised the share of linked store transactions to about 58% within six months, making the cross-channel recommendation use case viable (illustrative figures).",
      },
      {
        title: "Bank checking consent before a campaign",
        situation: "A bank planned a personalised cross-sell campaign across email, SMS and paid social audiences.",
        analysis: "The audit found consent stored as a single yes or no field without purpose or timestamp, and the paid social audience sync did not apply opt-outs. Only 46% of customers had a clear basis for marketing email.",
        outcome: "The bank introduced purpose-level consent records, fixed suppression in the audience sync and ran a preference-centre campaign to refresh consent before launching the cross-sell.",
      },
      {
        title: "Telecom real-time offers held back by latency",
        situation: "A telecom operator wanted to send top-up offers when prepaid balances ran low.",
        analysis: "Balance data reached the marketing platform in a nightly batch, so offers arrived up to a day late, after many customers had already topped up or switched.",
        outcome: "A streaming feed for the balance event only, rather than a full real-time rebuild, made the use case work at modest cost.",
      },
    ],
    visuals: [
      {
        type: "bars",
        title: "Data readiness scorecard",
        caption: "Consent coverage and offline identity match are the weakest dimensions, so they limit which use cases can launch first.",
        unit: "% ready",
        items: [
          { label: "Email completeness", value: 82 },
          { label: "Online identity match", value: 74 },
          { label: "Offline identity match", value: 31, highlight: true },
          { label: "Data freshness (< 24h)", value: 65 },
          { label: "Purpose-level consent", value: 46, highlight: true },
        ],
      },
      {
        type: "funnel",
        title: "From total customers to activatable audience",
        caption: "Each data gap removes customers from the usable audience, so a large customer base can shrink to a small one for personalisation.",
        stages: [
          { label: "Customers in base", value: 1000000 },
          { label: "With a matched profile", value: 740000 },
          { label: "With valid contact data", value: 610000 },
          { label: "With marketing consent", value: 380000 },
          { label: "Reachable in activation tool", value: 330000 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Identity match rate", formula: "Records linked to a unified profile ÷ total records in source", meaning: "How well systems can be joined around one customer." },
      { name: "Field completeness", formula: "Records with a valid value ÷ total records", meaning: "Availability of the fields that use cases depend on." },
      { name: "Duplicate rate", formula: "Duplicate profiles ÷ total profiles", meaning: "Risk of repeated or conflicting messages and inflated counts." },
      { name: "Consent coverage", formula: "Profiles with valid consent for purpose ÷ total profiles", meaning: "The share of the base that may lawfully be used for a given purpose." },
      { name: "Data latency", meaning: "Time from an event occurring to it being available for activation; must match the use case." },
    ],
    pitfalls: [
      "Buying a platform before checking whether the data to feed it exists and can be matched.",
      "Trying to fix all data everywhere instead of the fields and sources that priority use cases need.",
      "Treating consent as a single yes or no flag rather than purpose- and channel-specific, with records of when and how it was given.",
      "Assuming data syncs respect opt-outs without testing downstream suppression.",
      "Running a one-off audit with no ongoing quality monitoring or owners.",
    ],
    related: ["martech-capability", "use-case-roadmap", "contactability", "signal-loss"],
  },

  /* ------------------------------------------------------------------ */
  "use-case-roadmap": {
    overview: [
      "A MarTech use-case roadmap is a prioritised, time-sequenced plan of the marketing capabilities a company will launch, built from business use cases rather than from tools. A use case is a specific, valuable thing marketing wants to do, such as a cart abandonment journey, a churn-risk retention offer or suppressing existing customers from acquisition ads, defined with its audience, trigger, channel, data needs and expected outcome.",
      "Many organisations own powerful marketing platforms but use a fraction of their features, while new tools are bought to solve problems the existing stack could handle. The roadmap approach reverses this: list use cases, score each on business value and on feasibility with current data, technology and team skills, map them to features of vendors already owned, and sequence them into quarters so value is delivered early and capability builds step by step.",
      "It answers: which use cases should we launch first on the stack we already own? The output is a realistic plan that balances quick wins with foundation work, and makes clear where new investment is genuinely needed.",
    ],
    whenToUse: [
      "The company has invested in a CDP, marketing automation or CRM but is using few of its capabilities.",
      "A long list of requested campaigns and journeys has no agreed priority.",
      "A vendor selection or platform renewal is coming and the team needs to know what it actually needs.",
      "Leadership asks what return the MarTech investment is producing.",
      "Marketing, IT and data teams disagree about what to build next.",
      "Team capacity is limited and too many projects run in parallel without finishing.",
    ],
    howItWorks: [
      { step: "List use cases in a standard format", detail: "Collect use cases from marketing, CRM, product, sales and service teams. Describe each with the same fields: objective, audience, trigger, channels, data required, decisioning needed and the business metric it should move. Merge duplicates and split vague ideas into concrete use cases." },
      { step: "Score business value", detail: "Estimate value for each use case: audience size × expected uplift in conversion, retention or cost saving × value per outcome. Use illustrative ranges where data is uncertain, and add strategic weight for objectives such as compliance or customer experience." },
      { step: "Score feasibility", detail: "Rate each use case on data readiness (are the fields, identity and consent in place?), technology (does an owned tool support it?), effort and team skills. A simple 1–5 scale per dimension, averaged or weighted, is usually enough to separate easy from hard." },
      { step: "Map to existing vendor features", detail: "For each high-value use case, check whether current platforms already provide the capability, perhaps through an unused module or integration. Note genuine gaps separately; these become the business case for new tools or development." },
      { step: "Plot value against feasibility", detail: "Place use cases on a 2×2: quick wins (high value, high feasibility), strategic bets (high value, low feasibility, requiring foundations), fill-ins (low value, high feasibility) and deprioritised ideas (low value, low feasibility). This makes trade-offs visible to stakeholders." },
      { step: "Sequence into quarters", detail: "Schedule quick wins first to show value, and plan the foundation work (data, integrations) that unlocks strategic bets in later quarters. Respect team capacity, limit work in progress, and attach a measurement plan and owner to each use case." },
      { step: "Review and re-prioritise regularly", detail: "Each quarter, compare actual results with expected value, update feasibility as foundations land, and add new use cases. The roadmap is a living plan, not a one-off document." },
    ],
    plainWords: "Imagine you own a kitchen full of gadgets but mostly use the kettle. Instead of buying more gadgets, you list the meals you want to make, work out which would make people happiest and which you can already cook with what you have, then plan the easy, popular dishes for this week and the harder ones once you have learned a few new skills. A use-case roadmap does this for marketing tools.",
    examples: [
      {
        title: "Retailer with an under-used CDP",
        situation: "A retailer had paid for a customer data platform for two years and used it only to export email lists. Forty use case requests were pending.",
        analysis: "Scoring showed browse and cart abandonment, post-purchase cross-sell and suppression of recent buyers from acquisition ads were all high value and feasible with existing data and features. Personalised in-store offers scored high value but low feasibility because store identity matching was weak.",
        outcome: "Quarter one launched the three quick wins, which together were estimated to add around 3% to online revenue; store identity capture was scheduled as foundation work for quarter three (illustrative figures).",
      },
      {
        title: "Insurer avoiding an unnecessary purchase",
        situation: "An insurer planned to buy a new journey orchestration tool to run renewal reminders and lapse prevention.",
        analysis: "Mapping use cases to existing vendor features found that the current marketing automation platform supported multi-step, event-triggered journeys through a module already licensed but never configured.",
        outcome: "The insurer launched renewal and lapse journeys on the existing tool within one quarter and deferred the new purchase, redirecting budget to data integration.",
      },
      {
        title: "Telecom aligning teams on priorities",
        situation: "Marketing, IT and data teams at a telecom operator each had their own priority lists and projects stalled.",
        analysis: "A joint scoring workshop with agreed criteria produced a single ranked list. Several pet projects scored low on value once audience sizes were estimated.",
        outcome: "Work in progress was cut from twelve parallel projects to four, and the first three use cases launched in half the time previous projects had taken.",
      },
    ],
    visuals: [
      {
        type: "matrix",
        title: "Use cases by value and feasibility",
        caption: "Cart abandonment and buyer suppression are quick wins to launch first, while in-store personalisation needs foundations before it can deliver.",
        xLabel: "Feasibility on current stack",
        yLabel: "Business value",
        quadrants: ["Strategic bets: build foundations", "Quick wins: launch first", "Deprioritise", "Fill-ins: when capacity allows"],
        points: [
          { label: "Cart abandonment", x: 85, y: 80 },
          { label: "Buyer suppression in ads", x: 78, y: 62 },
          { label: "Post-purchase cross-sell", x: 70, y: 70 },
          { label: "In-store personalised offers", x: 25, y: 85 },
          { label: "Churn-risk retention offer", x: 40, y: 72 },
          { label: "Birthday email", x: 90, y: 25 },
          { label: "Weather-triggered ads", x: 20, y: 20 },
        ],
      },
      {
        type: "bars",
        title: "Estimated annual value by use case",
        caption: "A few use cases carry most of the value, which is why they should be sequenced first rather than spreading effort evenly.",
        unit: "k annual value",
        items: [
          { label: "Cart abandonment", value: 900, highlight: true },
          { label: "Post-purchase cross-sell", value: 650 },
          { label: "Churn-risk retention offer", value: 600 },
          { label: "Buyer suppression in ads", value: 300 },
          { label: "Birthday email", value: 80 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Use case value", formula: "Audience size × expected uplift × value per outcome", meaning: "Estimated annual impact used to rank use cases." },
      { name: "Feasibility score", formula: "Weighted average of data, technology, effort and skills scores", meaning: "How ready the organisation is to deliver the use case now." },
      { name: "Feature utilisation", formula: "Licensed platform features in active use ÷ features relevant to roadmap", meaning: "How much of the owned stack is put to work." },
      { name: "Time to value", meaning: "Time from approving a use case to its first measured results." },
      { name: "Realised vs expected value", formula: "Measured incremental value ÷ estimated value", meaning: "Checks estimates and improves future prioritisation." },
    ],
    pitfalls: [
      "Starting from tool features rather than business use cases, building capabilities nobody needs.",
      "Scoring value without estimating audience size, so niche ideas look as important as broad ones.",
      "Ignoring data and consent readiness in feasibility scores, leading to stalled projects.",
      "Running too many use cases in parallel for the team's capacity.",
      "Launching use cases without holdout groups or measurement, so value is never proven.",
    ],
    related: ["martech-capability", "data-governance", "next-best-action", "lifecycle"],
  },
};
