import type { FrameworkGuide } from "./types";

export const GUIDES_PART1: Record<string, FrameworkGuide> = {
  funnel: {
    overview: [
      "Funnel analysis breaks a customer journey into a sequence of stages, such as visit → product view → add to basket → checkout → purchase, and measures how many people make it from one stage to the next. Because each stage only receives the people who survived the previous one, the overall conversion rate is the product of the stage-to-stage rates, and a fall at any single step flows straight through to the bottom line.",
      "The idea goes back to the AIDA model (Attention, Interest, Desire, Action) described by advertising practitioners in the late nineteenth and early twentieth centuries, and it became the default lens for digital marketing once web analytics made every step measurable. Its strength is that it turns a vague complaint such as 'sales are down' into a specific, locatable leak.",
      "The question it answers is: which stage lost volume, for whom, and since when? A good funnel analysis does not stop at the aggregate view; it splits each step by channel, device, segment and time so that the team can see whether a drop is broad-based or confined to one slice of traffic.",
    ],
    whenToUse: [
      "Total conversions or sales have fallen and nobody can say where in the journey the loss happens.",
      "A site or app redesign, new checkout, pricing page or sign-up form has just gone live and you need to know whether it helped or hurt.",
      "Traffic is stable or growing but orders, leads or sign-ups are not following.",
      "One channel or device (for example mobile paid social) looks much weaker than others and you want to see which step explains it.",
      "You need to prioritise a backlog of UX or CRO ideas by the size of the leak they address.",
    ],
    howItWorks: [
      { step: "Define the stages", detail: "Write down 4–7 stages that every customer must pass through, each tied to a single, reliably tracked event. Stages should be sequential and mutually exclusive; if users can skip a step, either drop it or analyse it as a separate path." },
      { step: "Measure stage-to-stage conversion", detail: "For each stage, divide the number of users who reached it by the number who reached the previous stage, using the same time window and unique-user definition throughout. Record both the step rate and the cumulative rate from the top." },
      { step: "Trend each step over time", detail: "Plot every step rate weekly or daily for a period that covers before and after the change you are investigating. A genuine leak shows up as a step change in one rate while the others stay flat; seasonality moves several together." },
      { step: "Split by segment, channel and device", detail: "Repeat the funnel for the main cuts: new vs returning, traffic source, device, country, product category. Mix shifts often masquerade as conversion problems, for instance when cheap low-intent traffic grows and drags the blended rate down." },
      { step: "Isolate the largest change", detail: "Multiply each step's change in rate by the volume entering it to estimate lost conversions per step. The step with the biggest absolute loss, not the lowest rate, is where to focus first." },
      { step: "Diagnose and test", detail: "Pair the quantitative finding with session recordings, error logs, form analytics or user research at that step to understand why. Turn the hypothesis into a controlled test rather than shipping a fix blind." },
    ],
    plainWords: "Think of a lemonade stand. Lots of people walk past, some stop to look, fewer ask the price, and only some actually buy a cup. If sales drop, you want to know exactly which moment changed: did fewer people stop, or did they stop but walk off when they heard the price? Funnel analysis counts people at each of those moments so you can fix the right thing instead of guessing.",
    examples: [
      {
        title: "E-commerce checkout redesign",
        situation: "An online fashion retailer launched a new one-page checkout. Two weeks later, orders were down 12% on flat traffic.",
        analysis: "The step rates for product view → basket and basket → checkout start were unchanged. Checkout start → order fell from 62% to 49%, but only on mobile Safari. Error logs showed the address look-up widget failing to load on that browser.",
        outcome: "The widget was fixed within a day. Mobile Safari checkout completion recovered to 61%, restoring roughly 90% of the lost orders; the team added a browser-split funnel alert to catch similar regressions.",
      },
      {
        title: "Airline booking flow",
        situation: "An airline saw its booking conversion fall from 3.1% to 2.6% after introducing a fare-family selection page.",
        analysis: "Search → flight selection held steady, but flight selection → passenger details dropped from 48% to 39%. Recordings showed users comparing three fare columns, scrolling back and forth, then abandoning. The drop was concentrated among leisure travellers on short-haul routes.",
        outcome: "A simplified two-option layout with a clear default was tested against the three-column version. It lifted the step rate to 46% while keeping the share of upgraded fares close to the original.",
      },
      {
        title: "SaaS free-trial sign-up",
        situation: "A B2B SaaS company's trial sign-ups fell 20% month on month despite more website visits.",
        analysis: "Splitting by source revealed that a new display campaign had doubled visits to the pricing page but those visitors converted to sign-up at a third of the organic rate. The blended rate fell, yet the organic funnel was unchanged.",
        outcome: "There was no product leak; the issue was traffic quality. Display targeting was tightened and the team began reporting funnels by source so that mix effects were visible.",
      },
    ],
    visuals: [
      {
        type: "funnel",
        title: "Illustrative e-commerce funnel (weekly users)",
        caption: "Notice that the steepest proportional drop is between checkout start and order, which is where a broken step would show first.",
        stages: [
          { label: "Sessions", value: 100000 },
          { label: "Product view", value: 52000 },
          { label: "Add to basket", value: 14000 },
          { label: "Checkout start", value: 8400 },
          { label: "Order", value: 4100 },
        ],
      },
      {
        type: "bars",
        title: "Checkout completion by device, before vs after redesign",
        caption: "Only mobile Safari fell sharply, which points to a device-specific defect rather than a general design problem.",
        unit: "%",
        items: [
          { label: "Desktop before", value: 66 },
          { label: "Desktop after", value: 65 },
          { label: "Android before", value: 60 },
          { label: "Android after", value: 59 },
          { label: "iOS Safari before", value: 61 },
          { label: "iOS Safari after", value: 41, highlight: true },
        ],
      },
    ],
    keyMetrics: [
      { name: "Step conversion rate", formula: "Users reaching stage n ÷ users reaching stage n−1", meaning: "How well a single step converts; the main diagnostic number." },
      { name: "Cumulative conversion rate", formula: "Users reaching stage n ÷ users entering the funnel", meaning: "Overall efficiency of the journey up to a given point." },
      { name: "Lost conversions per step", formula: "Volume entering step × (old step rate − new step rate) × downstream rate", meaning: "Converts a rate change into a business impact, so steps can be ranked." },
      { name: "Drop-off rate", formula: "1 − step conversion rate", meaning: "Share of users who leave at a step; useful for reporting leaks." },
    ],
    pitfalls: [
      "Comparing blended funnels across periods without checking traffic mix, so a shift towards low-intent channels is misread as a product problem.",
      "Defining stages on events that are tracked inconsistently, for example a page view that fires twice or a step that some users can skip.",
      "Focusing on the step with the lowest rate rather than the step with the largest change or largest absolute loss.",
      "Using sessions at one stage and users at another, which makes step rates meaningless.",
      "Stopping at 'where' without investigating 'why' through qualitative evidence before launching fixes.",
    ],
    related: ["ux-diagnosis", "aarrr", "experimentation", "attribution"],
  },

  cac: {
    overview: [
      "Customer acquisition cost (CAC) is the total spend required to win one new customer. CAC and channel efficiency analysis calculates that cost separately for each acquisition channel and, crucially, sets it against the value those customers go on to generate. A channel that looks cheap can be expensive if its customers churn quickly, and a channel that looks costly can be the best investment if its customers stay and spend.",
      "The approach grew out of direct-response marketing and was formalised by subscription and SaaS businesses, where the ratio of lifetime value to CAC (LTV:CAC) and the CAC payback period became standard investor and board metrics. It applies equally well to retail, banking, telecoms and any business that pays to acquire customers.",
      "The question it answers is: which channels acquire valuable customers efficiently? The output is a ranked view of channels by cost and quality that supports a budget reallocation decision.",
    ],
    whenToUse: [
      "Marketing budget is being set or cut and you need an evidence-based view of where each pound or dollar works hardest.",
      "Blended CAC is rising and you want to know whether it is a channel-level problem or a mix shift.",
      "Some channels deliver lots of cheap customers who seem to disappear after the first purchase.",
      "Finance or the board asks for LTV:CAC or payback figures to judge growth efficiency.",
      "A new channel has been tested and you need to compare it fairly with established ones.",
    ],
    howItWorks: [
      { step: "Assemble spend by channel", detail: "Collect fully loaded acquisition cost per channel for a defined period: media, agency fees, creative production, affiliate commissions and, where relevant, sales costs. Be explicit about what is included so that numbers are comparable." },
      { step: "Count new customers by channel", detail: "Attribute each genuinely new customer to an acquisition source using a consistent rule, and exclude returning or reactivated customers. Note the attribution method because it changes the answer materially." },
      { step: "Compute CAC per channel", detail: "Divide channel spend by new customers from that channel. Also calculate blended CAC across all channels and paid-only CAC, since organic customers can flatter the blended figure." },
      { step: "Measure early value by source", detail: "Follow each channel's acquisition cohort for 3, 6 and 12 months and record gross margin, repeat rate and retention. Early value indicators allow decisions before full lifetime data exists." },
      { step: "Calculate LTV:CAC and payback", detail: "Divide expected gross-margin lifetime value by CAC for each channel, and compute how many months of margin it takes to recover CAC. Channels can then be compared on value per unit of spend rather than volume." },
      { step: "Reallocate and re-test", detail: "Shift budget from channels with weak ratios to those with headroom, watching for diminishing returns as spend scales. Validate with incrementality tests because attributed CAC can overstate channels that harvest existing demand." },
    ],
    plainWords: "Imagine you run a lemonade stall and pay people to hand out flyers in different places. Flyers at the bus stop bring 20 new customers for 10 pounds, flyers at the sports field bring 10 for 10 pounds. The bus stop looks better, but if the sports-field customers come back every day and the bus-stop ones only come once, the sports field is the better deal. CAC analysis is simply working out what each new customer cost you and how much they are worth afterwards.",
    examples: [
      {
        title: "Retail bank current accounts",
        situation: "A bank acquired current-account customers through price comparison sites, paid search and a cash-switching incentive. Comparison sites had the lowest CAC at 80 versus 140 for paid search.",
        analysis: "Cohort tracking showed 45% of comparison-site customers moved their salary away within six months after collecting the incentive, against 15% for paid search. On 12-month gross margin, paid search customers were worth 2.4 times as much.",
        outcome: "LTV:CAC was 1.6 for comparison sites and 3.2 for paid search. The bank capped comparison-site spend, added a salary-retention condition to the incentive and moved budget into search.",
      },
      {
        title: "E-commerce subscription box",
        situation: "A meal-kit brand's blended CAC rose from 45 to 62 over two quarters.",
        analysis: "Channel-level CAC was stable except for paid social, which had risen from 50 to 85 as spend tripled into lookalike audiences. The rising blended number was driven by paid social's growing share of the mix and its diminishing returns.",
        outcome: "Paid social spend was cut back to the level where marginal CAC stayed within target, and the freed budget funded a referral programme with a CAC of around 30.",
      },
      {
        title: "SaaS self-serve plan",
        situation: "A SaaS company compared content-led organic, paid search and a partner marketplace.",
        analysis: "The marketplace had a high CAC of 900 because of revenue share, but customers there had 30% higher net revenue retention and payback in 11 months against 14 for paid search.",
        outcome: "The company increased co-marketing with the marketplace and kept paid search at a lower, more efficient level.",
      },
    ],
    visuals: [
      {
        type: "bars",
        title: "LTV:CAC by acquisition channel",
        caption: "The cheapest channel on CAC alone (comparison sites) has the weakest value ratio once retention is included.",
        unit: "×",
        items: [
          { label: "Comparison sites", value: 1.6, highlight: true },
          { label: "Paid social", value: 2.1 },
          { label: "Paid search", value: 3.2 },
          { label: "Referral", value: 4.5 },
          { label: "Organic", value: 6.0 },
        ],
      },
      {
        type: "line",
        title: "Cumulative gross margin per customer vs CAC",
        caption: "Payback happens where each channel's margin line crosses its CAC; search pays back by month 6, comparison sites later and less surely.",
        xLabels: ["M1", "M3", "M6", "M9", "M12"],
        yLabel: "Cumulative margin per customer",
        series: [
          { name: "Paid search", points: [30, 80, 150, 210, 260] },
          { name: "Comparison sites", points: [25, 55, 85, 105, 120] },
          { name: "Search CAC", points: [140, 140, 140, 140, 140] },
          { name: "Comparison CAC", points: [80, 80, 80, 80, 80] },
        ],
      },
    ],
    keyMetrics: [
      { name: "CAC", formula: "Acquisition spend ÷ new customers acquired", meaning: "Cost of winning one new customer, per channel or blended." },
      { name: "LTV:CAC", formula: "Gross-margin lifetime value ÷ CAC", meaning: "Value created per unit of acquisition spend; below 1 destroys value." },
      { name: "CAC payback period", formula: "CAC ÷ monthly gross margin per customer", meaning: "Months needed to recover acquisition cost; drives cash requirements." },
      { name: "Marginal CAC", formula: "Change in spend ÷ change in new customers", meaning: "Cost of the next customer as spend scales; reveals diminishing returns." },
    ],
    pitfalls: [
      "Judging channels on CAC alone without accounting for the quality and retention of the customers they bring.",
      "Leaving costs out of the numerator (agency fees, creative, discounts, sales time), which makes some channels look artificially cheap.",
      "Using average CAC to plan increased spend when marginal CAC at higher budgets will be higher.",
      "Counting returning or reactivated customers as new, inflating channel performance.",
      "Trusting last-click attributed CAC for channels such as brand search that mainly capture demand created elsewhere.",
    ],
    related: ["clv", "paid-efficiency", "attribution", "cohort"],
  },

  attribution: {
    overview: [
      "Channel attribution is the practice of assigning credit for a conversion to the marketing touchpoints a customer encountered beforehand. Most journeys involve several touches, such as a social ad, a comparison article, an email and a brand search, and the attribution model decides how much of the sale each one receives.",
      "Early web analytics defaulted to last-click attribution, which gives all credit to the final touch. Alternatives include first-click, linear, time-decay, position-based and data-driven models. All of these are rules or statistical estimates of contribution; none of them on its own proves that a channel caused a sale, which is why modern practice pairs attribution with incrementality testing and marketing mix modelling.",
      "The question it answers is: which channels incrementally drive outcomes? Good attribution work shows how sensitive budget conclusions are to the choice of model and validates the important ones with experiments.",
    ],
    whenToUse: [
      "Reported ROAS for brand search, retargeting or affiliates looks remarkably high and you suspect they are capturing demand rather than creating it.",
      "Upper-funnel channels such as video, display or podcasts look ineffective under last click and are at risk of being cut.",
      "Different platforms each claim credit for the same conversions and their totals exceed actual sales.",
      "You are about to reallocate significant budget between channels.",
      "Tracking changes (cookie loss, consent) have altered reported performance and you need to know what is real.",
    ],
    howItWorks: [
      { step: "Audit the current model and data", detail: "Document which model each report uses, the lookback windows, and which touchpoints are actually captured. Check for gaps such as untracked offline media, view-through rules and consent-driven data loss." },
      { step: "Build a cross-channel touchpoint view", detail: "Join touchpoint logs to conversions at user or journey level, de-duplicating platform-reported conversions. Quantify how many journeys have one touch versus several." },
      { step: "Compare models side by side", detail: "Run last-click, first-click, linear, time-decay and, if available, data-driven models on the same data. Channels whose credit swings strongly between models are the ones where the decision is most uncertain." },
      { step: "Identify the decisions at stake", detail: "Focus on the channels where the model choice would change budget materially. There is no need to resolve uncertainty for channels whose ranking is stable under every model." },
      { step: "Validate with incrementality tests", detail: "Use geo holdouts, audience holdouts, platform lift studies or switch-off tests to measure the causal effect of the contested channels. Compare the incremental conversions with what each attribution model claimed." },
      { step: "Calibrate and operationalise", detail: "Adjust the working model or apply incrementality factors per channel so day-to-day reporting reflects tested reality. Re-test periodically, as incrementality changes with spend level and market conditions." },
    ],
    plainWords: "Picture a football team scoring a goal. The striker who kicked it in gets the cheers, but the defender who won the ball and the midfielder who passed it also made it happen. Last-click attribution is like giving the whole goal to the striker. Attribution analysis tries to share the credit fairly, and testing is like seeing what happens to the score when one player sits out for a match.",
    examples: [
      {
        title: "Retailer brand search",
        situation: "An electronics retailer's brand search campaign showed a ROAS of 18 under last click and absorbed a growing share of budget.",
        analysis: "A two-week geo test paused brand search bids in matched regions where the brand already ranked first organically. Total sales in test regions fell only 4% of what brand search had been credited with, because most clicks moved to the organic listing.",
        outcome: "Brand search spend was reduced by 60% in regions without competitor bidding, releasing budget for prospecting channels with demonstrably higher incremental returns.",
      },
      {
        title: "Telecom online video",
        situation: "A mobile operator's online video campaign looked weak under last click, with almost no attributed sign-ups.",
        analysis: "Under first-click and linear models video's share rose from 1% to 9%. A platform lift study then showed a statistically significant 6% increase in branded search and site visits in exposed audiences.",
        outcome: "Video was retained as an awareness driver and evaluated on incremental lift rather than last-click ROAS.",
      },
      {
        title: "Travel retargeting",
        situation: "A hotel booking site credited retargeting with a large share of bookings.",
        analysis: "An audience holdout of 10% of site visitors who were not shown retargeting ads booked at almost the same rate as exposed users, indicating low incrementality.",
        outcome: "Retargeting frequency caps were tightened and spend cut by half with no measurable fall in bookings.",
      },
    ],
    visuals: [
      {
        type: "bars",
        title: "Share of conversions credited to brand search under different views",
        caption: "Credit shrinks as you move from last click to tested incrementality, showing how much the model choice matters for this channel.",
        unit: "%",
        items: [
          { label: "Last click", value: 34, highlight: true },
          { label: "Time decay", value: 26 },
          { label: "Linear", value: 18 },
          { label: "First click", value: 9 },
          { label: "Incrementality test", value: 6 },
        ],
      },
      {
        type: "matrix",
        title: "Attributed ROAS vs tested incrementality",
        caption: "Channels in the bottom-right claim much more credit than they cause; the top-left channels are undervalued by attribution.",
        xLabel: "Attributed ROAS",
        yLabel: "Incrementality",
        quadrants: ["Undervalued: protect", "Proven: scale", "Weak: rethink", "Over-credited: cut back"],
        points: [
          { label: "Brand search", x: 90, y: 15 },
          { label: "Retargeting", x: 75, y: 25 },
          { label: "Online video", x: 15, y: 70 },
          { label: "Prospecting social", x: 60, y: 65 },
          { label: "Affiliates", x: 70, y: 35 },
          { label: "Display", x: 25, y: 30 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Attributed conversions", formula: "Sum of fractional credit assigned to the channel", meaning: "What the chosen model says a channel contributed." },
      { name: "Incremental conversions", formula: "Conversions in exposed group − conversions in holdout group (scaled)", meaning: "What the channel actually caused, measured by experiment." },
      { name: "Incrementality factor", formula: "Incremental conversions ÷ attributed conversions", meaning: "Correction to apply to attributed numbers for budgeting." },
      { name: "Incremental ROAS", formula: "Incremental revenue ÷ spend", meaning: "Return on spend net of sales that would have happened anyway." },
    ],
    pitfalls: [
      "Treating any attribution model as proof of causation rather than as a rule for sharing credit.",
      "Adding up platform-reported conversions, which double-count and exceed real sales.",
      "Cutting upper-funnel channels because they are invisible in last-click reports.",
      "Running underpowered incrementality tests and drawing conclusions from noise.",
      "Calibrating once and never revisiting as spend levels, creative and tracking change.",
    ],
    related: ["mmm", "signal-loss", "paid-efficiency", "experimentation"],
  },

  activation: {
    overview: [
      "First-value or onboarding analysis measures whether new customers reach the moment where they first experience the core benefit of a product, and how long that takes. This moment is often called activation or the 'aha' moment: the first completed booking, the first funded account, the first report shared, the first meal delivered on time.",
      "The concept was popularised by product-led growth teams, who found that a single early behaviour often separates customers who stay from those who leave. The insight applies just as much to banks (first salary deposit), telecoms (first top-up or port-in completed) and retailers (second purchase), because early experience shapes long-term retention.",
      "The question it answers is: do new customers reach first value, and how fast? The analysis defines the activation event, measures the distribution of time-to-value, and shows how much retention depends on getting there.",
    ],
    whenToUse: [
      "Sign-ups, account openings or trial starts are healthy but a large share of new customers go dormant within the first weeks.",
      "Free-trial to paid conversion is low or falling.",
      "Retention problems are concentrated in the first 30–90 days rather than among tenured customers.",
      "Onboarding emails, tutorials or set-up steps have been added over time and nobody knows which ones help.",
      "You need a leading indicator of retention that moves faster than monthly churn.",
    ],
    howItWorks: [
      { step: "Define candidate activation events", detail: "List early behaviours that plausibly reflect real value, such as completing set-up, inviting a colleague, making a first transaction or using a key feature twice. Each must be a clearly tracked event with a timestamp." },
      { step: "Test which event predicts retention", detail: "For each candidate, compare later retention of customers who did it within a fixed window against those who did not. Choose the event, and the threshold and window, that best separates retained from churned customers while remaining achievable for most users." },
      { step: "Measure activation rate and time-to-value", detail: "Calculate the share of new customers who activate within the window and plot the distribution of days from sign-up to activation. Look at medians and the long tail, not just averages." },
      { step: "Map the onboarding path", detail: "Break the route to activation into steps and run a funnel on them. Identify where new customers stall and which communications or prompts they receive at each point." },
      { step: "Segment the results", detail: "Split activation and time-to-value by acquisition channel, plan, device and customer type. Low activation in one source often indicates mis-set expectations in that channel's messaging." },
      { step: "Intervene and test", detail: "Remove friction, add guided set-up or trigger timely nudges for customers who have not activated by a given day. Measure the effect with controlled tests on activation and on subsequent retention." },
    ],
    plainWords: "Think of joining a football club. If you turn up, get handed a kit and play a real match in your first week, you are likely to keep coming. If you spend three weeks filling in forms and watching from the side, you probably drift away. Activation analysis finds the moment where newcomers first enjoy the real thing, and works out how to get more of them there sooner.",
    examples: [
      {
        title: "SaaS collaboration tool",
        situation: "A project-management SaaS had strong trial sign-ups but only 9% converted to paid.",
        analysis: "Users who created a project and invited at least two teammates within 7 days converted at 31%, versus 3% for others. Only 22% of trialists reached that point, and median time to the first invite was 5 days.",
        outcome: "The onboarding flow was rebuilt to prompt an invite immediately after the first project. Activation rose to 34% and trial-to-paid to 13% in the test group.",
      },
      {
        title: "Digital bank",
        situation: "A challenger bank opened many accounts, but 40% were never funded.",
        analysis: "Customers who received a first salary or transfer-in within 30 days had 12-month retention of 78% against 20% for those who did not. Funding stalled most at the step to add an external account, which required manual entry of details.",
        outcome: "Open-banking account linking and a day-3 reminder with a one-tap transfer were introduced. Funded-within-30-days rose from 60% to 71%.",
      },
      {
        title: "Food delivery app",
        situation: "A delivery app found many customers ordered once and never again.",
        analysis: "A second order within 14 days was the strongest predictor of a sustained customer. Late first deliveries cut the second-order rate by half.",
        outcome: "The team prioritised delivery reliability for first orders and introduced a targeted second-order offer, lifting the 14-day repeat rate by 6 percentage points.",
      },
    ],
    visuals: [
      {
        type: "line",
        title: "Retention of activated vs non-activated customers",
        caption: "The gap opens in the first month and never closes, which is why the activation event matters so much.",
        xLabels: ["M1", "M2", "M3", "M6", "M12"],
        yLabel: "% still active",
        series: [
          { name: "Activated in 7 days", points: [88, 80, 75, 68, 60] },
          { name: "Not activated", points: [45, 28, 20, 13, 9] },
        ],
      },
      {
        type: "funnel",
        title: "Path to activation for new sign-ups",
        caption: "The largest loss is between first login and completed set-up, so that is where onboarding effort should go.",
        stages: [
          { label: "Signed up", value: 10000 },
          { label: "First login", value: 8200 },
          { label: "Set-up complete", value: 4300 },
          { label: "Core action", value: 3100 },
          { label: "Activated", value: 2200 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Activation rate", formula: "New customers reaching activation within N days ÷ new customers", meaning: "Share of new customers who experience core value early." },
      { name: "Time-to-value", formula: "Median days from sign-up to activation event", meaning: "Speed of reaching value; shorter is usually better for retention." },
      { name: "Retention lift from activation", formula: "Retention of activated − retention of non-activated", meaning: "How much the activation event matters to long-term outcomes." },
      { name: "Trial-to-paid conversion", formula: "Paid conversions ÷ trial starts", meaning: "Commercial outcome of onboarding for trial-based products." },
    ],
    pitfalls: [
      "Choosing an activation event because it is easy to track rather than because it predicts retention.",
      "Assuming correlation is causation: highly motivated users both activate and retain, so forcing the event may not lift retention as much as hoped.",
      "Setting an activation definition so demanding that few users can reach it, making it useless as a target.",
      "Adding more onboarding messages instead of removing friction from the product path.",
      "Measuring only averages, which hide a long tail of customers who never reach value.",
    ],
    related: ["funnel", "cohort", "aarrr", "ux-diagnosis"],
  },

  cohort: {
    overview: [
      "Cohort analysis groups customers by a shared starting point, usually the month or week they were acquired, and tracks how each group behaves over time. Instead of a single blended retention figure, you see a set of curves or a triangle table that shows month-1, month-2, month-3 retention for each cohort separately.",
      "The technique comes from epidemiology and demography, where cohorts are followed to separate the effects of age, period and generation. In marketing it solves a common problem: overall active-customer numbers mix new and old customers, so a fall can come from weaker new cohorts, from tenured customers leaving, or from a change in acquisition volume.",
      "The question it answers is: is the decline in new or tenured cohorts, and at what lifecycle point? It tells you whether to look at acquisition quality and onboarding, or at the experience of established customers.",
    ],
    whenToUse: [
      "Active customers or repeat revenue are falling and you need to know whether it is a new-customer or existing-customer issue.",
      "A change in acquisition strategy, pricing, product or onboarding happened and you want to see whether later cohorts behave differently.",
      "Blended retention looks stable but you suspect strong old cohorts are masking weaker new ones.",
      "You need inputs for a lifetime value model or payback calculation.",
      "Different acquisition channels or promotions may be bringing customers of different quality.",
    ],
    howItWorks: [
      { step: "Choose the cohort definition", detail: "Most often this is the month of first purchase or sign-up, but it can be the first product bought, the campaign, or the plan. Keep the cohort size large enough for stable rates, typically several hundred customers or more." },
      { step: "Define the retention measure", detail: "Decide what counts as retained in a period: any purchase, an active session, a paid subscription, or revenue retained. Use the same definition for every cohort and period." },
      { step: "Build the cohort table", detail: "Create a table with cohorts as rows and periods since acquisition as columns, filling each cell with the share of the original cohort still retained. Also build a revenue version if spend per customer matters." },
      { step: "Plot and compare the curves", detail: "Plot each cohort's retention against months since acquisition on one chart. Look for curves that start lower (onboarding or quality issue), drop faster at a specific month (a lifecycle event such as end of promotion), or flatten at a lower level (weaker long-term fit)." },
      { step: "Find where curves diverge", detail: "Identify the period at which recent cohorts separate from older ones, and read across diagonals to spot calendar events affecting all cohorts at once, such as a price change or outage." },
      { step: "Split by segment", detail: "Repeat the analysis by channel, offer, region or product to locate which groups drive the change. This turns an observation into a specific hypothesis for action." },
    ],
    plainWords: "Imagine a leaky bucket that you refill with a new jug of water every month. If the bucket is emptier than before, it could be that the new jugs are smaller, or that the bucket has a new hole near the bottom, or that old water is draining faster. Cohort analysis labels each jug of water and watches it separately, so you can see exactly which water is leaking and when.",
    examples: [
      {
        title: "Subscription streaming service",
        situation: "A streaming service saw monthly active subscribers flatten despite steady sign-ups.",
        analysis: "Cohorts acquired after a three-months-for-one-pound promotion launched had month-4 retention of 38%, against 62% for earlier cohorts. The curves were identical until month 3 and then dropped sharply when the full price began.",
        outcome: "The promotion was replaced with a one-month trial and a content-led onboarding series. Month-4 retention of new cohorts recovered to 55% at a lower acquisition volume but higher net subscriber growth.",
      },
      {
        title: "Grocery e-commerce",
        situation: "An online grocer's repeat order rate declined over a year.",
        analysis: "New cohorts retained as well as old ones. However, all cohorts showed a simultaneous dip in the same calendar month, visible as a diagonal in the table, coinciding with a delivery fee increase.",
        outcome: "The issue was a period effect rather than cohort quality. A delivery subscription was introduced for frequent shoppers, and repeat rates for tenured cohorts recovered.",
      },
      {
        title: "Mobile game",
        situation: "A mobile game studio needed to know whether a new tutorial had worked.",
        analysis: "Day-1 retention of post-launch cohorts rose from 35% to 41%, but day-30 retention was unchanged at 6%, meaning the tutorial helped the first session but not long-term engagement.",
        outcome: "The team shifted focus to mid-game progression and social features, where the cohort curves showed the main drop.",
      },
    ],
    visuals: [
      {
        type: "line",
        title: "Retention curves by acquisition cohort",
        caption: "The promotional cohorts track the older ones until month 3, then fall away when full price begins.",
        xLabels: ["M1", "M2", "M3", "M4", "M5", "M6"],
        yLabel: "% of cohort retained",
        series: [
          { name: "Jan cohort", points: [85, 74, 68, 62, 59, 57] },
          { name: "Apr cohort", points: [84, 73, 67, 61, 58, 56] },
          { name: "Jul cohort (promo)", points: [92, 86, 81, 38, 33, 31] },
          { name: "Oct cohort (promo)", points: [93, 87, 82, 37, 32, 30] },
        ],
      },
    ],
    keyMetrics: [
      { name: "Period-n retention", formula: "Customers in cohort active in period n ÷ cohort size", meaning: "Share of a cohort still active after n periods." },
      { name: "Revenue retention", formula: "Cohort revenue in period n ÷ cohort revenue in period 1", meaning: "Captures spend changes as well as customer loss." },
      { name: "Terminal retention", formula: "Retention level where the curve flattens", meaning: "Size of the loyal core; drives lifetime value." },
      { name: "Cohort LTV", formula: "Sum over periods of retained customers × margin per customer ÷ cohort size", meaning: "Value per acquired customer, for comparison with CAC." },
    ],
    pitfalls: [
      "Comparing cohorts at different ages, for example judging a three-month-old cohort against a two-year-old one on cumulative metrics.",
      "Using cohorts too small to give stable rates, then reading noise as signal.",
      "Missing calendar effects that hit every cohort at once and show up as diagonals rather than rows.",
      "Changing the definition of 'active' midway through the series.",
      "Looking only at customer counts when spend per retained customer is changing as well.",
    ],
    related: ["churn", "clv", "activation", "cac"],
  },

  rfm: {
    overview: [
      "RFM segmentation scores every customer on three behavioural dimensions: Recency (how recently they last bought), Frequency (how often they buy) and Monetary value (how much they spend). Combining the three gives a simple, transparent segmentation that separates best customers from those who are slipping away or were only ever occasional.",
      "RFM has its roots in direct mail and catalogue marketing from the mid-twentieth century, when marketers found that recent, frequent, high-spending customers responded far better to mailings. It remains popular because it needs only transaction history, is easy to explain and translates directly into CRM actions.",
      "The question it answers is: which value segments are shrinking or migrating? Tracked over time, RFM shows customers moving from 'champions' to 'at risk', which is often the earliest sign of a retention problem among valuable customers.",
    ],
    whenToUse: [
      "You need a quick, data-light segmentation to target CRM campaigns differently.",
      "Revenue from the top customer tier appears to be declining and you want to see which customers are slipping.",
      "Win-back or loyalty budgets need to be focused on the customers where they will make the most difference.",
      "Marketing currently sends the same message to everyone and you want to start personalising.",
      "You need an input to propensity models or next-best-action rules.",
    ],
    howItWorks: [
      { step: "Prepare transaction data", detail: "Aggregate each customer's transactions over a fixed lookback, often 12 or 24 months: date of last purchase, number of purchases and total spend or margin. Exclude returns and test accounts." },
      { step: "Score R, F and M", detail: "Rank customers on each dimension and assign scores, commonly 1 to 5 by quintile, with 5 the best. For recency a more recent date gets a higher score; for businesses with naturally low frequency, use business-relevant thresholds instead of quintiles." },
      { step: "Build named segments", detail: "Combine scores into a manageable number of segments, typically 6–10, such as Champions (high R, F, M), Loyal, Potential loyalists, New, At risk (low R, high F and M), Hibernating and Lost. Names should suggest an action." },
      { step: "Profile each segment", detail: "Report size, share of revenue, average order value, margin and channel preferences per segment. Usually a small share of customers accounts for a large share of value." },
      { step: "Track migration between periods", detail: "Re-score customers each month or quarter and build a migration matrix showing how many moved between segments. Flows from Champions to At risk are the critical warning sign." },
      { step: "Assign actions", detail: "Define a CRM treatment and objective for each segment, such as recognition for Champions, reactivation for At risk and low-cost contact for Lost. Test treatments against holdouts." },
    ],
    plainWords: "Think about the regulars at a corner shop. Some came in yesterday, come every day and buy a lot; others used to come every day but have not been seen for a month; others came once a year ago. The shopkeeper treats them differently without thinking about it. RFM simply gives every customer three scores, how recently, how often and how much, so a business can do the same thing for millions of people.",
    examples: [
      {
        title: "Fashion retailer",
        situation: "A fashion retailer's revenue fell 6% year on year while customer numbers were stable.",
        analysis: "RFM migration showed that 18% of last year's Champions had moved to At risk, against a usual 9%. These customers had not bought since a change in the returns policy. Champions represented 8% of customers and 41% of revenue.",
        outcome: "A targeted service-recovery programme restored free returns for top segments and offered early access to new collections. Half of the at-risk group purchased again within 90 days.",
      },
      {
        title: "Quick-service restaurant app",
        situation: "A QSR chain sent the same weekly discount to all app users.",
        analysis: "RFM scoring revealed that frequent, recent customers would have bought anyway, while lapsed customers barely responded to the generic offer.",
        outcome: "Discounts were withdrawn from Champions and replaced with recognition messages, while lapsed segments received stronger, time-limited offers. Promotional cost fell by a quarter with no fall in visits.",
      },
      {
        title: "Online wine merchant",
        situation: "A wine merchant wanted to grow repeat purchases from first-time buyers.",
        analysis: "New customers with a high first-order value were twice as likely to become Loyal within a year as those with low first orders.",
        outcome: "A tailored second-purchase journey with curated recommendations was built for high-value new customers.",
      },
    ],
    visuals: [
      {
        type: "matrix",
        title: "RFM segments by recency and frequency",
        caption: "Customers in the bottom-right were once frequent but have gone quiet; they are the priority for retention action.",
        xLabel: "Frequency",
        yLabel: "Recency",
        quadrants: ["New / promising", "Champions", "Lost", "At risk"],
        points: [
          { label: "Champions", x: 85, y: 88 },
          { label: "Loyal", x: 70, y: 65 },
          { label: "New", x: 15, y: 90 },
          { label: "Potential", x: 35, y: 70 },
          { label: "At risk", x: 80, y: 20 },
          { label: "Hibernating", x: 35, y: 30 },
          { label: "Lost", x: 10, y: 8 },
        ],
      },
      {
        type: "bars",
        title: "Share of customers vs share of revenue by segment",
        caption: "Champions are a small group but account for the largest slice of revenue.",
        unit: "% of revenue",
        items: [
          { label: "Champions (8%)", value: 41, highlight: true },
          { label: "Loyal (14%)", value: 24 },
          { label: "At risk (10%)", value: 15 },
          { label: "Potential (18%)", value: 11 },
          { label: "Other (50%)", value: 9 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Recency", formula: "Days since last purchase", meaning: "The strongest single predictor of future purchase in most businesses." },
      { name: "Frequency", formula: "Number of purchases in the lookback window", meaning: "Habit strength and relationship depth." },
      { name: "Monetary value", formula: "Total spend or margin in the lookback window", meaning: "Economic importance of the customer." },
      { name: "Segment migration rate", formula: "Customers moving from segment A to B ÷ customers in A at start", meaning: "Speed at which customers improve or deteriorate." },
    ],
    pitfalls: [
      "Using quintiles blindly when most customers buy once, which collapses frequency into meaningless scores.",
      "Scoring monetary value on revenue when margin varies widely across products.",
      "Treating RFM as a static snapshot rather than tracking migration over time.",
      "Creating dozens of score combinations that nobody can act on.",
      "Giving the heaviest discounts to Champions who would have bought anyway.",
    ],
    related: ["winback", "loyalty-tiering", "clv", "frequency"],
  },

  churn: {
    overview: [
      "Churn driver analysis explains why customers leave and how early the signs appear. It defines churn precisely, compares the characteristics and behaviour of churned and retained customers, builds a model of churn propensity, and identifies the window in which an intervention can still change the outcome.",
      "The method is standard in telecoms, banking, insurance, utilities and subscription businesses, where a contract or account makes churn explicit. It also applies to non-contractual businesses such as retail, where churn has to be inferred from a period of inactivity.",
      "The question it answers is: what predicts churn and how early can we see it? The goal is not only an accurate model but an actionable one: drivers the business can influence and a lead time long enough to act.",
    ],
    whenToUse: [
      "Cancellations, non-renewals or account closures are rising.",
      "A price increase, service change or competitor launch is suspected of driving customers away.",
      "Retention offers are being sent broadly and you need to target them at genuinely at-risk customers.",
      "Customer service or complaint volumes have increased and you want to know their impact on attrition.",
      "Leadership wants a forecast of churn and the revenue at risk.",
    ],
    howItWorks: [
      { step: "Define churn", detail: "In contractual businesses, churn is a cancellation or non-renewal date. In non-contractual ones, set an inactivity threshold based on the natural purchase cycle, for example no purchase in three times the typical inter-purchase interval. Distinguish voluntary churn from involuntary churn such as failed payments." },
      { step: "Profile churners vs retained customers", detail: "Compare the two groups on tenure, product holding, price paid, usage trends, service contacts, complaints, payment issues and channel. Look at changes in behaviour before churn, not just static attributes." },
      { step: "Build a propensity model", detail: "Use logistic regression or tree-based models to estimate each customer's probability of churning in the next period. Validate on out-of-time data and check that the top-scored decile contains a much higher share of churners than average." },
      { step: "Interpret the drivers", detail: "Rank features by contribution and separate those the business can influence (service failures, price, missing features) from those it cannot (age, location). Validate key drivers with customer research or exit surveys." },
      { step: "Define the intervention window", detail: "Measure how far in advance the model detects risk and how long customers take from first warning sign to churn. Interventions need to land inside that window, after risk is visible but before the decision is made." },
      { step: "Test retention actions", detail: "Target high-risk, high-value customers with treatments matched to their driver, and keep a random holdout to measure saved customers net of those who would have stayed anyway." },
    ],
    plainWords: "Think of a football club noticing that some players are about to quit. Before they quit they miss a few training sessions, complain about the coach or stop chatting with the team. If the club spots those signs early, the coach can have a word and keep them. Churn analysis looks back at everyone who left, finds the warning signs they showed beforehand, and then watches for those signs in the people who are still here.",
    examples: [
      {
        title: "Mobile network operator",
        situation: "A telecom operator's monthly postpaid churn rose from 1.2% to 1.6% after a mid-contract price rise.",
        analysis: "Churners were three times as likely to have had two or more network complaints in the previous 60 days and twice as likely to be out of contract. The model flagged most churners 45–60 days before they ported out.",
        outcome: "Customers with high risk and network complaints received proactive service follow-up and a tailored handset upgrade offer. Churn in the treated group fell by 22% relative to the holdout.",
      },
      {
        title: "Insurance renewals",
        situation: "A motor insurer lost a rising share of customers at renewal.",
        analysis: "Renewal price increase above 15% and absence of a claims interaction were the strongest drivers. Customers who had made a well-handled claim were more loyal than those who had never claimed.",
        outcome: "Price increases for low-risk, long-tenure customers were capped and renewal communications were redesigned to explain the price. Retention rose 3 points.",
      },
      {
        title: "SaaS subscription",
        situation: "A SaaS business wanted to reduce annual plan non-renewal.",
        analysis: "Declining weekly active seats over the last quarter of the contract and the departure of the original champion user predicted non-renewal four months ahead.",
        outcome: "Customer success teams were alerted when seat usage fell below 60% of licensed seats, triggering re-onboarding sessions.",
      },
    ],
    visuals: [
      {
        type: "bars",
        title: "Churn rate by top drivers",
        caption: "Repeated network complaints multiply the chance of leaving, making them the most actionable driver.",
        unit: "% monthly churn",
        items: [
          { label: "All customers", value: 1.6 },
          { label: "Out of contract", value: 3.0 },
          { label: "Price rise > 10%", value: 2.7 },
          { label: "2+ complaints", value: 4.8, highlight: true },
          { label: "Failed payment", value: 3.5 },
        ],
      },
      {
        type: "bars",
        title: "Share of churners captured by risk decile",
        caption: "A good model concentrates churners in the top deciles so retention budget can be focused there.",
        unit: "% of churners",
        items: [
          { label: "Decile 1", value: 38, highlight: true },
          { label: "Decile 2", value: 21 },
          { label: "Decile 3", value: 13 },
          { label: "Deciles 4–6", value: 18 },
          { label: "Deciles 7–10", value: 10 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Churn rate", formula: "Customers lost in period ÷ customers at start of period", meaning: "Basic speed of customer loss." },
      { name: "Revenue churn", formula: "Recurring revenue lost in period ÷ recurring revenue at start", meaning: "Value-weighted loss, important when customers differ in size." },
      { name: "Model lift", formula: "Churn rate in top decile ÷ overall churn rate", meaning: "How much better than random the model targets risk." },
      { name: "Saved customers", formula: "Churn rate in holdout − churn rate in treated group, × treated customers", meaning: "Incremental impact of retention action." },
    ],
    pitfalls: [
      "Defining churn loosely, so that seasonal pauses are counted as losses or real losses are missed.",
      "Building a highly accurate model that only detects churn a few days before it happens, leaving no time to act.",
      "Targeting retention offers on propensity alone without considering customer value and responsiveness.",
      "Mistaking correlates (low usage) for root causes (a broken feature or poor service).",
      "Measuring retention campaigns without a holdout, crediting them with customers who would have stayed anyway.",
    ],
    related: ["engagement-decay", "winback", "cohort", "nps-drivers"],
  },

  lifecycle: {
    overview: [
      "Customer lifecycle analysis maps the stages a customer passes through, such as prospect, new, onboarding, active, growing, at risk, lapsed and won back, and checks whether each stage and each key moment is covered by relevant communication. It brings together CRM, product and service touchpoints in one view of the customer relationship.",
      "Lifecycle marketing grew from database marketing and became central once marketing automation allowed messages to be triggered by behaviour rather than sent on a calendar. Mature CRM programmes typically rely on a set of always-on triggered journeys rather than one-off campaigns.",
      "The question it answers is: which lifecycle moments are not covered by relevant communication? The output is a gap-and-overlap map and a prioritised list of triggers to build or fix.",
    ],
    whenToUse: [
      "CRM is mostly calendar-driven batch campaigns with few behavioural triggers.",
      "Customers receive too many overlapping messages from different teams or, at critical moments, none at all.",
      "Retention or repeat purchase is weak and you want to see where communication could help.",
      "A new CRM platform or customer data platform is being implemented and you need to prioritise use cases.",
      "Different business units each own parts of the customer journey with no shared view.",
    ],
    howItWorks: [
      { step: "Define lifecycle stages", detail: "Agree a small set of mutually exclusive stages with precise data-based entry and exit rules, for example 'New: first purchase within 30 days' or 'At risk: no purchase in 1.5 times the usual interval'. Make sure every customer sits in exactly one stage at any time." },
      { step: "Size each stage and its flows", detail: "Count customers in each stage and the monthly flows between them. This shows where the base is concentrated and where customers get stuck or leak." },
      { step: "Inventory current communications", detail: "List every triggered journey, batch campaign, service message and in-product prompt, with audience, trigger, channel, frequency and owner. Plot them against stages and key moments." },
      { step: "Identify gaps and overlaps", detail: "Highlight stages or moments with no relevant message (for example no welcome series or no lapse prevention) and those where several teams contact the same customer at once. Check contact frequency per customer per stage." },
      { step: "Prioritise triggers", detail: "Estimate the value of each missing or improved trigger by stage size, conversion potential and ease of build. Prioritise the few journeys that address the biggest flows, typically onboarding, second purchase and lapse prevention." },
      { step: "Build, govern and measure", detail: "Implement triggers with clear suppression and priority rules, and measure each journey against a holdout. Review the lifecycle map regularly as products and behaviours change." },
    ],
    plainWords: "Think of how a good sports coach treats a player over a season: a warm welcome on the first day, extra help in the first weeks, encouragement when they play well, a check-in when they miss practice, and a call if they stop turning up. Lifecycle analysis checks whether a business does the same for its customers, making sure the right message arrives at each moment and that nobody is either ignored or pestered.",
    examples: [
      {
        title: "Online retailer",
        situation: "A homeware retailer sent two batch newsletters a week to all subscribers and had a single welcome email.",
        analysis: "Lifecycle mapping showed that 60% of first-time buyers never bought again, yet there was no second-purchase journey and no lapse prevention. Meanwhile loyal customers received up to nine messages a week from different teams.",
        outcome: "A three-step post-purchase journey and a lapse-risk trigger were launched, with a frequency cap of four messages a week. Second-purchase rate within 90 days rose from 24% to 29% against holdout.",
      },
      {
        title: "Retail bank",
        situation: "A bank's credit card customers rarely used the card after the introductory period.",
        analysis: "There were no communications between month 3 and the end of the promotional rate at month 12, the period when usage habits formed.",
        outcome: "Usage-based triggers were introduced in months 2–6, featuring relevant spend categories. Active card usage at month 12 rose by 8 points.",
      },
      {
        title: "Telecom broadband",
        situation: "A broadband provider found customers frequently cancelled at contract end.",
        analysis: "The first proactive communication arrived only after the contract had expired. No messages celebrated value delivered or prompted upgrades mid-contract.",
        outcome: "A pre-renewal journey starting 90 days before contract end was introduced with personalised offers.",
      },
    ],
    visuals: [
      {
        type: "cycle",
        title: "Customer lifecycle stages",
        caption: "Each arrow is a moment where a triggered message can help move the customer forward or stop them slipping back.",
        steps: ["Prospect", "New customer", "Onboarding", "Active", "Growing", "At risk", "Lapsed", "Won back"],
      },
      {
        type: "bars",
        title: "Triggered journeys per lifecycle stage (current state)",
        caption: "Active customers are over-served while onboarding and at-risk stages have little or no coverage.",
        unit: "journeys",
        items: [
          { label: "Prospect", value: 2 },
          { label: "Onboarding", value: 1, highlight: true },
          { label: "Active", value: 9 },
          { label: "At risk", value: 0, highlight: true },
          { label: "Lapsed", value: 1 },
        ],
      },
    ],
    keyMetrics: [
      { name: "Stage transition rate", formula: "Customers moving from stage A to B in period ÷ customers in A at start", meaning: "Health of each lifecycle step." },
      { name: "Trigger coverage", formula: "Eligible customers receiving a relevant message ÷ eligible customers", meaning: "Whether a moment is actually addressed." },
      { name: "Contact frequency", formula: "Messages per customer per week by stage", meaning: "Detects over- and under-communication." },
      { name: "Journey incremental lift", formula: "Target conversion rate − holdout conversion rate", meaning: "Value of each triggered journey." },
    ],
    pitfalls: [
      "Defining stages loosely so customers fall into several stages or none.",
      "Building many journeys without suppression and priority rules, creating message overload.",
      "Mapping only marketing messages and ignoring service, billing and product communications that customers also experience.",
      "Measuring journeys on opens and clicks rather than incremental behaviour change against a holdout.",
      "Treating the lifecycle map as a one-off exercise rather than a living operating model.",
    ],
    related: ["next-best-action", "contactability", "activation", "winback"],
  },

  "engagement-decay": {
    overview: [
      "Engagement decay analysis tracks how a customer's interaction with a brand, such as logins, app sessions, email opens, store visits or product usage, fades in the weeks and months before they churn. It treats churn not as a single event but as the end of a gradual decline that is often visible well in advance.",
      "The idea is closely related to churn modelling and to the concept of customer health scores used by SaaS customer success teams. Its distinctive contribution is the time dimension: it measures how engagement evolves relative to the moment of churn, which reveals when the decline begins and how long the window for intervention is.",
      "The question it answers is: when does engagement start to decay relative to churn? Once the typical decay pattern is known, thresholds can be set to trigger action while customers are still reachable.",
    ],
    whenToUse: [
      "Churn appears sudden but you suspect earlier warning signs exist in behavioural data.",
      "Email open rates, app sessions or logins are falling across the base.",
      "Customer success or CRM teams need early-warning alerts rather than lagging churn reports.",
      "Many customers are technically active but rarely interact, and you want to know which of them are at risk.",
      "Retention interventions tend to arrive too late to make a difference.",
    ],
    howItWorks: [
      { step: "Choose engagement signals", detail: "Select a handful of behaviours that reflect genuine value, such as sessions, core feature use, transactions and service interactions. Avoid relying solely on email opens, which are distorted by privacy features." },
      { step: "Build an engagement index", detail: "Combine signals into a weekly or monthly score per customer, normalised to their own past baseline or to peer averages. A simple weighted sum is often enough; weights can be informed by each signal's correlation with retention." },
      { step: "Align histories to churn date", detail: "For churned customers, re-index time so that the churn date is zero and plot average engagement for the weeks before. Do the same for retained customers over a comparable period." },
      { step: "Plot decay curves", detail: "Compare the churner curve with the retained curve to see when they diverge and how steep the decline becomes. Split by segment, as decay patterns differ between products and customer types." },
      { step: "Set decay thresholds", detail: "Define a trigger, for example 'engagement index below 60% of personal baseline for three consecutive weeks', that captures a large share of future churners early with an acceptable false-alarm rate." },
      { step: "Act on the trigger and test", detail: "Connect the threshold to a re-engagement journey, outreach or product prompt, and measure saved customers against a holdout." },
    ],
    plainWords: "Think of a friend who used to message you every day, then every few days, then once a week, and then stopped entirely. Looking back, you could see the friendship cooling well before it ended. Engagement decay analysis looks for that same slow fade in how customers use a product, so the business can reach out while there is still time.",
    examples: [
      {
        title: "Fitness app subscription",
        situation: "A fitness app found most cancellations happened at renewal, which seemed to come without warning.",
        analysis: "Aligning usage to cancellation date showed that churners' weekly workouts began falling about 10 weeks before cancelling and dropped below one a week around six weeks before. Retained users stayed above three.",
        outcome: "A trigger at fewer than one workout a week for two weeks launched personalised plan suggestions and a challenge invitation. Cancellations in the treated group fell 15% against holdout.",
      },
      {
        title: "B2B SaaS",
        situation: "A SaaS company's customer success managers learned about at-risk accounts only at renewal negotiations.",
        analysis: "An account-level health index of active seats, key feature use and support tickets showed decline starting four to five months before non-renewal.",
        outcome: "CSMs received alerts when an account's index fell 30% below its baseline, giving them time to run adoption reviews.",
      },
      {
        title: "Online bank",
        situation: "A digital bank wanted to spot customers drifting to competitors before they closed accounts.",
        analysis: "Card transactions and salary deposits declined gradually for about three months before closure, while app logins stayed steady until the end.",
        outcome: "The decay trigger was based on transaction share rather than logins, which identified at-risk customers much earlier.",
      },
    ],
    visuals: [
      {
        type: "line",
        title: "Engagement index in the weeks before churn",
        caption: "The churner curve starts to separate about 10 weeks out, which defines the intervention window.",
        xLabels: ["−16w", "−12w", "−10w", "−8w", "−6w", "−4w", "−2w", "0"],
        yLabel: "Engagement index (baseline = 100)",
        series: [
          { name: "Churned", points: [100, 98, 92, 78, 60, 42, 25, 10] },
          { name: "Retained", points: [100, 101, 99, 100, 98, 99, 100, 99] },
        ],
      },
    ],
    keyMetrics: [
      { name: "Engagement index", formula: "Weighted sum of normalised engagement signals", meaning: "Single score of customer interaction, tracked over time." },
      { name: "Decay rate", formula: "(Current index − baseline) ÷ baseline", meaning: "Proportional decline from the customer's own normal level." },
      { name: "Lead time", formula: "Median weeks between threshold breach and churn", meaning: "Length of the window available for intervention." },
      { name: "Trigger precision", formula: "Flagged customers who later churn ÷ all flagged customers", meaning: "Share of alerts that were genuine risk." },
    ],
    pitfalls: [
      "Relying on email opens, which are inflated or hidden by privacy features and say little about value.",
      "Using absolute thresholds that ignore differences in normal usage between customers.",
      "Setting thresholds so tight that they flag customers only days before churn.",
      "Confusing seasonal dips, such as holidays, with genuine decay.",
      "Sending generic 'we miss you' messages instead of addressing the reason engagement fell.",
    ],
    related: ["churn", "lifecycle", "winback", "cohort"],
  },

  frequency: {
    overview: [
      "Purchase frequency analysis studies how often customers buy and how long they wait between purchases, known as the inter-purchase interval. It detects whether customers are buying less often, which customers are slowing down, and what the natural rhythm of buying is for each product or segment.",
      "Frequency is often the biggest lever in retail, grocery, quick-service restaurants and consumer goods, where customers rarely leave outright but gradually shift spend elsewhere. A small lengthening of the interval across many customers can erode revenue significantly while headline customer counts look unchanged.",
      "The question it answers is: are customers buying less often, and which ones? The analysis also provides the timing needed to schedule replenishment reminders and to define when a customer should be considered lapsed.",
    ],
    whenToUse: [
      "Revenue is falling while active customer counts and average order value are stable.",
      "Competitors, a new format or economic pressure may be pulling a share of customers' spend away.",
      "You want to time reminders and offers to customers' natural buying cycles.",
      "You need a data-based definition of lapse or churn for a non-subscription business.",
      "Loyalty or subscription programmes aim to increase visit frequency and need a baseline.",
    ],
    howItWorks: [
      { step: "Compute inter-purchase intervals", detail: "For each customer, sort transactions by date and calculate the days between consecutive purchases. Summarise per customer (median interval) and overall as a distribution." },
      { step: "Establish the natural cycle", detail: "Look at the distribution of intervals by product category or segment. Peaks show typical rhythms, such as weekly grocery shopping or monthly pet food, and the long tail shows when customers are likely lapsing." },
      { step: "Compare periods", detail: "Compare intervals and purchases per customer between equivalent periods, controlling for seasonality. Separate changes in frequency from changes in the number of active customers and in order value." },
      { step: "Split by value segment", detail: "Repeat the comparison for high-, mid- and low-value customers, channels and regions. A frequency drop among the most valuable customers matters far more than one among occasional buyers." },
      { step: "Decompose revenue change", detail: "Break revenue change into active customers × purchases per customer × average order value. This shows how much of the change frequency explains." },
      { step: "Act on timing", detail: "Use each customer's expected next-purchase date to trigger reminders or offers slightly before it, and flag customers who pass a multiple of their usual interval as at risk." },
    ],
    plainWords: "Imagine a family that buys bread from your bakery every Saturday. If they start coming every other Saturday, you have not lost them as customers, but you have lost half their bread money. Frequency analysis watches how long people wait between visits, so you notice when regulars start coming less often and can remind them at just the right time.",
    examples: [
      {
        title: "Grocery retailer",
        situation: "A grocer's like-for-like sales fell 4% while the number of active loyalty card holders was flat.",
        analysis: "The median interval for high-value households grew from 7 to 9 days, and their purchases per quarter fell 14%. Basket size was unchanged. The decline was concentrated near stores where a discounter had opened.",
        outcome: "A personalised weekly offer targeted at high-value households near competitor stores restored much of their frequency, recovering roughly half the lost sales in those areas.",
      },
      {
        title: "Quick-service restaurant",
        situation: "A coffee chain's app users visited less often after a price increase.",
        analysis: "Daily visitors (intervals of 1–2 days) were stable, but customers with 3–5 day intervals stretched to 6–8 days. Revenue decomposition showed frequency explained 70% of the decline.",
        outcome: "A visit-streak reward for the mid-frequency segment lifted their visits by 9% against holdout.",
      },
      {
        title: "Pet supplies e-commerce",
        situation: "A pet supplies site wanted to grow repeat orders of food.",
        analysis: "Most customers re-ordered dry food every 28–35 days depending on pack size, and many who passed 45 days had switched to another retailer.",
        outcome: "Replenishment reminders were sent at day 25, with a subscription offer. Repeat order rate within 40 days rose by 11 points.",
      },
    ],
    visuals: [
      {
        type: "bars",
        title: "Distribution of inter-purchase intervals (grocery, high-value households)",
        caption: "Most repeat purchases happen within 7–14 days, so a gap beyond 21 days is a clear early lapse signal.",
        unit: "% of intervals",
        items: [
          { label: "1–6 days", value: 28 },
          { label: "7–13 days", value: 41, highlight: true },
          { label: "14–20 days", value: 17 },
          { label: "21–34 days", value: 9 },
          { label: "35+ days", value: 5 },
        ],
      },
      {
        type: "waterfall",
        title: "Revenue change decomposition",
        caption: "Lower purchase frequency explains most of the revenue fall, while customer numbers and basket size barely moved.",
        unit: "£m",
        items: [
          { label: "Last year", value: 100, total: true },
          { label: "Active customers", value: -0.5 },
          { label: "Purchase frequency", value: -3.4 },
          { label: "Average basket", value: -0.1 },
          { label: "This year", value: 96, total: true },
        ],
      },
    ],
    keyMetrics: [
      { name: "Purchase frequency", formula: "Orders in period ÷ active customers in period", meaning: "Average number of purchases per customer." },
      { name: "Inter-purchase interval", formula: "Days between consecutive purchases (median per customer)", meaning: "The rhythm of buying, used for timing and lapse definitions." },
      { name: "Revenue decomposition", formula: "Revenue = active customers × frequency × average order value", meaning: "Shows which driver explains revenue change." },
      { name: "Overdue rate", formula: "Customers past 1.5× their usual interval ÷ active customers", meaning: "Share of customers showing early signs of slowing or lapsing." },
    ],
    pitfalls: [
      "Comparing frequencies across periods of different length or season without adjustment.",
      "Using a single average interval for all products and customers when rhythms differ widely.",
      "Reading lower frequency as disengagement when customers are buying larger baskets less often.",
      "Ignoring customers with only one purchase, who have no interval but may be the biggest opportunity.",
      "Sending reminders after the expected purchase date rather than shortly before it.",
    ],
    related: ["rfm", "loyalty-tiering", "winback", "churn"],
  },
};
