import type { ProblemType } from "@/domain/types";

/** Reusable diagnostic framework library (spec §12). */
export interface DiagnosticFramework {
  id: string;
  name: string;
  category: "Acquisition" | "Activation" | "Retention" | "Winback" | "Loyalty" | "Personalization" | "CRM" | "MarTech" | "Measurement";
  description: string;
  problemTypes: ProblemType[];
  keywords: string[];
  requiredData: string[];
  answers: string;
  steps: string[];
}

export const FRAMEWORKS: DiagnosticFramework[] = [
  {
    id: "funnel",
    name: "Funnel Analysis",
    category: "Acquisition",
    description: "Locate where prospects or customers leak between stages.",
    problemTypes: ["acquisition", "conversion", "activation"],
    keywords: ["funnel", "drop", "conversion", "checkout", "signup", "redesign", "abandon"],
    requiredData: ["Stage-level volumes", "Web/app behaviour", "Channel source"],
    answers: "Which stage lost volume, for whom, and since when?",
    steps: ["Define stages", "Measure stage conversion over time", "Split by segment/channel/device", "Isolate the step with the largest change"],
  },
  {
    id: "cac",
    name: "CAC & Channel Efficiency",
    category: "Acquisition",
    description: "Assess acquisition cost and quality by channel.",
    problemTypes: ["acquisition"],
    keywords: ["cac", "cost per", "paid", "media", "acquisition cost", "lead"],
    requiredData: ["Spend by channel", "New customers by channel", "Early value by channel"],
    answers: "Which channels acquire valuable customers efficiently?",
    steps: ["Compute CAC by channel", "Compare cohort value by source", "Compute LTV:CAC", "Reallocate"],
  },
  {
    id: "attribution",
    name: "Channel Attribution",
    category: "Measurement",
    description: "Understand channel contribution beyond last click.",
    problemTypes: ["acquisition", "conversion"],
    keywords: ["attribution", "last click", "roas", "channel mix"],
    requiredData: ["Touchpoint logs", "Conversions", "Spend"],
    answers: "Which channels incrementally drive outcomes?",
    steps: ["Audit current model", "Compare models", "Validate with incrementality tests"],
  },
  {
    id: "activation",
    name: "First-Value / Onboarding Analysis",
    category: "Activation",
    description: "Measure time-to-value and onboarding completion.",
    problemTypes: ["activation", "engagement"],
    keywords: ["onboarding", "activation", "first value", "trial", "setup", "dormant account"],
    requiredData: ["Signup date", "Key product events", "Onboarding communications"],
    answers: "Do new customers reach first value, and how fast?",
    steps: ["Define activation event", "Measure time-to-value distribution", "Compare activated vs not on retention"],
  },
  {
    id: "cohort",
    name: "Cohort Analysis",
    category: "Retention",
    description: "Compare retention curves of customer cohorts over time.",
    problemTypes: ["retention", "engagement", "loyalty", "activation"],
    keywords: ["retention", "repeat", "cohort", "churn", "decline", "returning"],
    requiredData: ["Customer-level transaction history", "Acquisition date", "Acquisition source"],
    answers: "Is the decline in new or tenured cohorts, and at what lifecycle point?",
    steps: ["Build acquisition cohorts", "Plot retention curves", "Identify the period where curves diverge", "Split by segment"],
  },
  {
    id: "rfm",
    name: "RFM Segmentation",
    category: "Retention",
    description: "Segment by recency, frequency and monetary value.",
    problemTypes: ["retention", "winback", "loyalty", "personalization"],
    keywords: ["high value", "frequency", "recency", "segment", "vip", "value"],
    requiredData: ["Transaction history"],
    answers: "Which value segments are shrinking or migrating?",
    steps: ["Score R, F and M", "Build segments", "Track migration between periods"],
  },
  {
    id: "churn",
    name: "Churn Driver Analysis",
    category: "Retention",
    description: "Identify drivers and early signals of churn.",
    problemTypes: ["retention", "winback"],
    keywords: ["churn", "lapse", "cancel", "attrition", "renewal", "leaving"],
    requiredData: ["Churn label", "Behavioural signals", "Service interactions", "Pricing changes"],
    answers: "What predicts churn and how early can we see it?",
    steps: ["Define churn", "Profile churners vs retained", "Model propensity", "Define intervention window"],
  },
  {
    id: "lifecycle",
    name: "Customer Lifecycle Analysis",
    category: "CRM",
    description: "Map lifecycle stages, triggers and communication coverage.",
    problemTypes: ["retention", "crm", "engagement", "loyalty"],
    keywords: ["lifecycle", "journey", "crm", "trigger", "communication"],
    requiredData: ["Lifecycle stage definitions", "Campaign calendar", "Engagement data"],
    answers: "Which lifecycle moments are not covered by relevant communication?",
    steps: ["Define stages", "Map current communications", "Identify gaps and overlaps", "Prioritise triggers"],
  },
  {
    id: "engagement-decay",
    name: "Engagement Decay",
    category: "Retention",
    description: "Track how engagement deteriorates before churn.",
    problemTypes: ["engagement", "retention"],
    keywords: ["engagement", "open rate", "inactive", "usage drop"],
    requiredData: ["Engagement events over time"],
    answers: "When does engagement start to decay relative to churn?",
    steps: ["Build engagement index", "Plot decay curves", "Set decay thresholds"],
  },
  {
    id: "frequency",
    name: "Purchase Frequency Analysis",
    category: "Retention",
    description: "Analyse inter-purchase intervals and frequency shifts.",
    problemTypes: ["retention", "loyalty", "monetization"],
    keywords: ["frequency", "repeat", "inter-purchase", "basket"],
    requiredData: ["Transaction history"],
    answers: "Are customers buying less often, and which ones?",
    steps: ["Compute inter-purchase intervals", "Compare periods", "Split by value segment"],
  },
  {
    id: "winback",
    name: "Dormancy & Winback",
    category: "Winback",
    description: "Prioritise lapsed customers by previous value and intent.",
    problemTypes: ["winback", "retention"],
    keywords: ["winback", "win-back", "lapsed", "dormant", "reactivat"],
    requiredData: ["Last activity date", "Historic value", "Intent signals"],
    answers: "Which lapsed customers are worth winning back, and how?",
    steps: ["Define dormancy windows", "Score previous value and intent", "Design offers by segment", "Hold out control"],
  },
  {
    id: "loyalty-tiering",
    name: "Loyalty & Tiering Assessment",
    category: "Loyalty",
    description: "Evaluate loyalty programme design and engagement.",
    problemTypes: ["loyalty", "retention"],
    keywords: ["loyalty", "points", "tier", "rewards", "frequent flyer", "membership"],
    requiredData: ["Member activity", "Tier movement", "Redemption"],
    answers: "Does the programme change behaviour for valuable customers?",
    steps: ["Compare members vs non-members", "Analyse tier migration", "Assess benefit perception"],
  },
  {
    id: "next-best-action",
    name: "Personalisation / Next-Best-Action",
    category: "Personalization",
    description: "Assess segment, context, intent and propensity-driven decisioning.",
    problemTypes: ["personalization", "crm", "monetization"],
    keywords: ["personalis", "personaliz", "recommendation", "next best", "cross-sell", "upsell", "relevance"],
    requiredData: ["Profile", "Behaviour", "Product holdings", "Response history"],
    answers: "Are we making the right offer to the right customer at the right moment?",
    steps: ["Audit decisioning", "Define eligibility and propensity", "Arbitrate offers", "Test vs control"],
  },
  {
    id: "contactability",
    name: "CRM Contactability & Frequency",
    category: "CRM",
    description: "Evaluate reach, consent, suppression and fatigue.",
    problemTypes: ["crm", "engagement", "retention"],
    keywords: ["unsubscribe", "fatigue", "frequency", "consent", "deliverability", "contactable"],
    requiredData: ["Consent status", "Send logs", "Unsubscribes"],
    answers: "Can we reach customers, and are we over- or under-communicating?",
    steps: ["Measure contactable base", "Analyse frequency vs engagement", "Define caps and preference centre"],
  },
  {
    id: "martech-capability",
    name: "MarTech Capability Assessment",
    category: "MarTech",
    description: "Assess data, decisioning, activation and measurement capability.",
    problemTypes: ["martech", "personalization", "crm"],
    keywords: ["cdp", "crm", "martech", "stack", "platform", "integration", "tool"],
    requiredData: ["Current stack", "Integration architecture", "Use-case backlog"],
    answers: "Which capability gaps block the required use cases?",
    steps: ["List use cases", "Map required capabilities", "Score current maturity", "Identify gaps"],
  },
  {
    id: "experimentation",
    name: "Experimentation & Incrementality",
    category: "Measurement",
    description: "Establish control groups and incrementality measurement.",
    problemTypes: ["conversion", "crm", "personalization", "acquisition", "retention"],
    keywords: ["test", "a/b", "incremental", "control group", "experiment"],
    requiredData: ["Assignment logs", "Outcome data"],
    answers: "What is the true incremental effect of our marketing?",
    steps: ["Define hypothesis", "Size sample", "Randomise", "Measure lift"],
  },
  {
    id: "ux-diagnosis",
    name: "UX & Technical Performance Diagnosis",
    category: "Acquisition",
    description: "Check site/app experience and performance changes.",
    problemTypes: ["conversion"],
    keywords: ["redesign", "website", "page speed", "ux", "mobile", "checkout", "bug", "release"],
    requiredData: ["Web analytics", "Release log", "Performance metrics"],
    answers: "Did a product or technical change cause the drop?",
    steps: ["Align metric change with release timeline", "Compare device/browser", "Review session evidence"],
  },
];

export function getFramework(id: string): DiagnosticFramework | undefined {
  return FRAMEWORKS.find((f) => f.id === id);
}
