/**
 * Industry intelligence library. Content is qualitative by design: the platform
 * never ships numeric "benchmarks" it cannot source. Where a benchmark would
 * help, `benchmarkGuidance` tells the strategist what to compare against.
 */
export interface IndustryProfile {
  id: string;
  name: string;
  businessModels: string[];
  lifecycle: string[];
  kpis: string[];
  commonProblems: string[];
  drivers: string[];
  martechStack: string[];
  channels: string[];
  economicModel: string;
  frameworks: string[];
  benchmarkGuidance: string;
}

export const INDUSTRIES: IndustryProfile[] = [
  {
    id: "airline",
    name: "Airlines",
    businessModels: ["B2C", "B2B (corporate travel)", "Transaction"],
    lifecycle: ["Search", "Booking", "Pre-travel", "Travel", "Post-travel", "Repeat booking", "Loyalty", "Advocacy"],
    kpis: ["Repeat booking rate", "Load factor", "Yield / RASK", "Ancillary revenue per passenger", "Direct booking share", "Loyalty member share of revenue", "NPS"],
    commonProblems: ["Declining repeat bookings", "OTA dependency", "Low ancillary attach", "Loyalty programme disengagement", "Price-led switching"],
    drivers: ["Fare", "Schedule", "Route availability", "Loyalty benefits", "Service experience", "Ancillary products", "Competitor pricing", "Frequency", "Customer value", "Travel purpose"],
    martechStack: ["PSS / reservation system", "Loyalty platform", "CDP", "Marketing automation", "Revenue management", "Personalisation engine", "Customer service platform"],
    channels: ["Email", "Push", "In-app", "WhatsApp", "Website personalisation", "Paid search", "Metasearch", "Call centre"],
    economicModel: "Revenue = passengers × average fare + ancillaries; value concentrated in frequent and corporate travellers.",
    frameworks: ["cohort", "rfm", "lifecycle", "churn", "loyalty-tiering", "funnel"],
    benchmarkGuidance: "Compare repeat booking by route, travel purpose and loyalty tier against your own prior-year cohorts before external benchmarks.",
  },
  {
    id: "banking",
    name: "Banking",
    businessModels: ["B2C", "B2B", "Subscription-like (relationship)"],
    lifecycle: ["Awareness", "Application", "Onboarding", "Activation", "Product usage", "Cross-sell", "Primacy", "Advocacy"],
    kpis: ["Products per customer", "Primacy rate", "Activation rate", "Attrition rate", "Cost to acquire", "Deposit balances", "Digital adoption"],
    commonProblems: ["Low activation after account opening", "Dormant accounts", "Weak cross-sell", "Digital drop-off in applications"],
    drivers: ["Onboarding experience", "Rates and fees", "Digital experience", "Relevance of offers", "Service quality", "Trust"],
    martechStack: ["Core banking", "CRM", "CDP", "Marketing automation", "Decisioning / next-best-action", "Consent management", "Analytics"],
    channels: ["Mobile app", "Email", "SMS", "Push", "Branch", "Call centre", "Relationship managers"],
    economicModel: "Value = net interest margin + fee income across product holdings; lifetime value driven by primacy and tenure.",
    frameworks: ["funnel", "activation", "lifecycle", "churn", "next-best-action"],
    benchmarkGuidance: "Benchmark activation and attrition by product and acquisition channel; regulatory constraints apply to targeting.",
  },
  {
    id: "insurance",
    name: "Insurance",
    businessModels: ["B2C", "B2B2C (brokers/partners)", "Subscription (policy)"],
    lifecycle: ["Awareness", "Quote", "Purchase", "Onboarding", "Claims", "Renewal", "Cross-sell", "Advocacy"],
    kpis: ["Quote-to-bind rate", "Renewal / retention rate", "Lapse rate", "Claims satisfaction", "Policies per customer", "Combined ratio"],
    commonProblems: ["Renewal leakage", "Price-shopping at renewal", "Low engagement between renewals", "Quote abandonment"],
    drivers: ["Price at renewal", "Claims experience", "Engagement mid-term", "Channel (broker vs direct)", "Product fit"],
    martechStack: ["Policy admin system", "CRM", "Marketing automation", "CDP", "Pricing engine", "Analytics"],
    channels: ["Email", "SMS", "Agents / brokers", "Call centre", "Web", "App"],
    economicModel: "Value = premiums over tenure minus claims and servicing cost; retention economics dominate.",
    frameworks: ["churn", "lifecycle", "funnel", "cohort"],
    benchmarkGuidance: "Compare renewal rates by tenure, product and price change bucket.",
  },
  {
    id: "retail",
    name: "Retail",
    businessModels: ["B2C", "Omnichannel", "Transaction"],
    lifecycle: ["Awareness", "Consideration", "First purchase", "Second purchase", "Repeat", "Loyalty", "Advocacy"],
    kpis: ["Repeat purchase rate", "Purchase frequency", "Average order value", "Customer lifetime value", "Active customers", "Loyalty penetration"],
    commonProblems: ["Falling purchase frequency", "Low second-purchase conversion", "Discount dependency", "Store-to-digital identity gaps"],
    drivers: ["Assortment", "Price and promotion", "Convenience", "Store experience", "Personalisation", "Loyalty benefits"],
    martechStack: ["POS", "E-commerce platform", "CRM", "Loyalty platform", "CDP", "ESP", "Recommendation engine"],
    channels: ["Email", "SMS", "WhatsApp", "Push", "In-store", "Paid social", "Direct mail"],
    economicModel: "Value = active customers × frequency × AOV × margin.",
    frameworks: ["rfm", "cohort", "frequency", "lifecycle", "winback"],
    benchmarkGuidance: "Track 2nd-purchase rate and 90-day repeat by acquisition cohort and channel.",
  },
  {
    id: "ecommerce",
    name: "E-commerce",
    businessModels: ["B2C", "Marketplace", "D2C", "Subscription"],
    lifecycle: ["Awareness", "Visit", "Browse", "Cart", "Purchase", "Second purchase", "Repeat", "Loyalty", "Advocacy"],
    kpis: ["Conversion rate", "Cart abandonment", "Repeat purchase rate", "AOV", "CAC", "LTV:CAC", "Contribution margin per order"],
    commonProblems: ["Retention drop after first/second purchase", "Rising CAC", "Conversion decline", "Promo dependency"],
    drivers: ["Delivery experience", "Price competitiveness", "Assortment", "Site UX", "Personalisation", "Returns experience"],
    martechStack: ["Commerce platform", "ESP / marketing automation", "CDP", "Product analytics", "Recommendation engine", "Attribution"],
    channels: ["Email", "SMS", "WhatsApp", "Push", "Paid social", "Paid search", "Affiliates", "Onsite personalisation"],
    economicModel: "Value = orders × AOV × contribution margin; LTV:CAC governs growth efficiency.",
    frameworks: ["funnel", "cohort", "rfm", "churn", "attribution", "winback"],
    benchmarkGuidance: "Use your own cohort curves; compare M1/M3/M6 repeat rates by acquisition source.",
  },
  {
    id: "hospitality",
    name: "Hospitality",
    businessModels: ["B2C", "B2B (corporate/MICE)", "Transaction"],
    lifecycle: ["Inspiration", "Search", "Booking", "Pre-stay", "Stay", "Post-stay", "Rebooking", "Loyalty"],
    kpis: ["Direct booking share", "RevPAR", "Repeat guest rate", "Ancillary spend", "Review score", "Loyalty enrolment"],
    commonProblems: ["OTA dependency", "Low repeat stays", "Weak pre-stay upsell", "Guest data fragmentation"],
    drivers: ["Price parity", "Location", "Experience quality", "Loyalty value", "Reviews"],
    martechStack: ["PMS", "CRS", "CRM", "Loyalty", "Marketing automation", "Reputation management"],
    channels: ["Email", "WhatsApp", "Website", "Metasearch", "OTA", "Front desk"],
    economicModel: "Value = room nights × ADR + ancillaries − distribution cost.",
    frameworks: ["lifecycle", "cohort", "funnel", "loyalty-tiering"],
    benchmarkGuidance: "Compare direct vs OTA guests on repeat rate and net value after commission.",
  },
  {
    id: "telecom",
    name: "Telecom",
    businessModels: ["B2C", "B2B", "Subscription"],
    lifecycle: ["Acquisition", "Onboarding", "Usage", "Upgrade", "Renewal", "Retention", "Advocacy"],
    kpis: ["Churn rate", "ARPU", "Net adds", "Upsell rate", "NPS", "Cost to serve"],
    commonProblems: ["Contract-end churn", "Price-led switching", "Low data upsell", "Service-driven churn"],
    drivers: ["Network quality", "Price", "Device offers", "Service experience", "Bundles"],
    martechStack: ["BSS/OSS", "CRM", "Decisioning engine", "CDP", "Marketing automation", "Churn models"],
    channels: ["SMS", "App", "Push", "Call centre", "Retail stores", "Email"],
    economicModel: "Value = ARPU × tenure − cost to serve; small churn changes have large value impact.",
    frameworks: ["churn", "lifecycle", "next-best-action", "cohort"],
    benchmarkGuidance: "Analyse churn by contract stage, tenure and service incident exposure.",
  },
  {
    id: "saas",
    name: "SaaS",
    businessModels: ["B2B", "B2C", "Subscription", "Product-led", "Sales-led"],
    lifecycle: ["Awareness", "Trial / signup", "Activation", "Adoption", "Expansion", "Renewal", "Advocacy"],
    kpis: ["Activation rate", "Time to value", "Net revenue retention", "Gross churn", "Expansion revenue", "CAC payback", "Product qualified leads"],
    commonProblems: ["Low trial conversion", "Poor activation", "Logo churn", "Low expansion"],
    drivers: ["Onboarding", "Time to first value", "Feature adoption", "Customer success coverage", "Pricing / packaging"],
    martechStack: ["Product analytics", "CRM", "Marketing automation", "Customer success platform", "CDP", "Billing"],
    channels: ["In-app", "Email", "Customer success", "Sales", "Webinars", "Community"],
    economicModel: "Value = ARR × net revenue retention; CAC payback governs efficiency.",
    frameworks: ["activation", "funnel", "cohort", "churn", "engagement-decay"],
    benchmarkGuidance: "Define the activation event; compare cohorts by plan and acquisition source.",
  },
  {
    id: "automotive",
    name: "Automotive",
    businessModels: ["B2C", "Dealer network (B2B2C)", "Aftersales / service", "Subscription & financing"],
    lifecycle: ["Awareness", "Research", "Configure", "Test drive", "Purchase / finance", "Delivery", "Service", "Repurchase", "Advocacy"],
    kpis: ["Lead-to-test-drive rate", "Test-drive-to-sale rate", "Cost per sale", "Service retention", "Repurchase / loyalty rate", "Finance penetration", "Connected-car activation"],
    commonProblems: ["Low lead quality from dealers", "Aftersales leakage to independents", "Long consideration cycle drop-off", "OEM–dealer data silos", "EV transition messaging"],
    drivers: ["Model and price", "Financing offers", "Dealer experience", "Brand perception", "Service convenience", "Residual values", "Incentives"],
    martechStack: ["DMS", "CRM", "Lead management", "CDP", "Configurator analytics", "Marketing automation", "Connected-car platform"],
    channels: ["Paid search", "Paid social", "Configurator / website", "Dealers", "Email", "Events", "Connected-car / app"],
    economicModel: "Value = vehicle margin + finance & insurance + aftersales over ownership; aftersales retention drives lifetime value.",
    frameworks: ["funnel", "b2b-funnel", "lead-scoring", "lifecycle", "cohort", "brand-funnel"],
    benchmarkGuidance: "Compare lead-to-sale by source and dealer; track service retention by vehicle age.",
  },
  {
    id: "travel",
    name: "Travel & OTAs",
    businessModels: ["B2C", "Marketplace", "Transaction", "Package / tour operator"],
    lifecycle: ["Inspiration", "Search", "Compare", "Book", "Pre-trip", "Trip", "Post-trip review", "Rebook"],
    kpis: ["Look-to-book", "Repeat booking rate", "App share of bookings", "Take rate", "Paid marketing as % of revenue", "Cancellation rate"],
    commonProblems: ["Dependence on paid search/metasearch", "Low app adoption", "Low repeat bookings", "Seasonality", "Price comparison churn"],
    drivers: ["Price", "Inventory breadth", "Trust and reviews", "Loyalty / rewards", "Booking UX", "Flexibility policies"],
    martechStack: ["Booking engine", "CDP", "Marketing automation", "Product analytics", "Attribution / MMP", "Recommendation engine"],
    channels: ["Paid search", "Metasearch", "App push", "Email", "Affiliates", "Paid social", "SEO"],
    economicModel: "Value = bookings × average booking value × take rate − paid acquisition cost.",
    frameworks: ["funnel", "paid-efficiency", "cohort", "app-growth", "seo-audit", "loyalty-tiering"],
    benchmarkGuidance: "Compare repeat-booking cohorts by first-booking channel; separate brand from non-brand paid.",
  },
  {
    id: "healthcare",
    name: "Healthcare & Pharma",
    businessModels: ["B2C (patients)", "B2B (HCPs, payers)", "Provider network", "Subscription (health plans)"],
    lifecycle: ["Awareness", "Symptom search", "Appointment / prescription", "Onboarding", "Adherence", "Follow-up", "Advocacy"],
    kpis: ["Appointment conversion", "No-show rate", "Patient retention", "Adherence / refill rate", "HCP reach & frequency", "Patient acquisition cost"],
    commonProblems: ["Low adherence", "No-shows", "Fragmented patient journeys", "Strict consent/regulatory limits", "HCP engagement fatigue"],
    drivers: ["Trust", "Access and convenience", "Clinical outcomes", "Cost / coverage", "Reminders and education"],
    martechStack: ["EHR / practice management", "CRM (e.g. Veeva / Health Cloud)", "Consent management", "Marketing automation", "Analytics"],
    channels: ["Email", "SMS", "Patient portal / app", "Field reps", "Search", "Medical content"],
    economicModel: "Value = patient lifetime visits/prescriptions × margin; adherence and retention dominate.",
    frameworks: ["funnel", "lifecycle", "churn", "nps-drivers", "data-governance", "content-strategy"],
    benchmarkGuidance: "Measure adherence and no-show rates by cohort; all targeting must respect HIPAA/GDPR-style constraints.",
  },
  {
    id: "education",
    name: "Education & EdTech",
    businessModels: ["B2C", "B2B (institutions)", "Subscription", "Course / cohort-based"],
    lifecycle: ["Awareness", "Enquiry / lead", "Counselling / trial", "Enrolment", "Learning", "Completion", "Renewal / upsell", "Alumni referral"],
    kpis: ["Lead-to-enrolment rate", "Cost per enrolment", "Course completion", "Renewal rate", "Refund rate", "Referral share"],
    commonProblems: ["High CAC per enrolment", "Low completion", "Seasonal intake dependency", "Poor lead quality"],
    drivers: ["Outcomes / placement", "Price and financing", "Brand credibility", "Counselling quality", "Learning experience"],
    martechStack: ["LMS", "CRM / admissions", "Marketing automation", "Product analytics", "Lead scoring"],
    channels: ["Paid search", "Paid social", "Webinars", "Counsellors / sales", "Email", "WhatsApp", "Referral"],
    economicModel: "Value = enrolments × fee − acquisition and delivery cost; completion drives referrals and renewal.",
    frameworks: ["funnel", "lead-scoring", "activation", "cohort", "referral-loop", "paid-efficiency"],
    benchmarkGuidance: "Compare lead-to-enrolment by source and counsellor; completion by cohort start date.",
  },
  {
    id: "real_estate",
    name: "Real Estate",
    businessModels: ["B2C", "Developer / builder", "Brokerage", "Rental / PropTech platform"],
    lifecycle: ["Awareness", "Search", "Enquiry", "Site visit", "Booking", "Purchase / lease", "Possession", "Referral"],
    kpis: ["Cost per qualified lead", "Lead-to-site-visit rate", "Visit-to-booking rate", "Sales velocity", "Cancellation rate", "Referral share"],
    commonProblems: ["Low-quality portal leads", "Slow lead response", "Long sales cycles", "Channel partner dependency"],
    drivers: ["Location", "Price and payment plans", "Developer trust", "Amenities", "Speed of follow-up"],
    martechStack: ["CRM", "Lead management", "Marketing automation", "Call tracking", "Analytics"],
    channels: ["Property portals", "Paid search", "Paid social", "Channel partners", "WhatsApp", "Events", "Site visits"],
    economicModel: "Value = units sold × margin − cost per sale (media + brokerage).",
    frameworks: ["funnel", "lead-scoring", "b2b-funnel", "paid-efficiency", "attribution"],
    benchmarkGuidance: "Track lead-to-visit-to-booking by source and response time.",
  },
  {
    id: "media",
    name: "Media, Streaming & Publishing",
    businessModels: ["Subscription", "Ad-supported", "Hybrid (AVOD/SVOD)", "B2C"],
    lifecycle: ["Discovery", "Sign-up / trial", "First engagement", "Habit formation", "Subscription", "Renewal", "Win-back"],
    kpis: ["Trial-to-paid", "Monthly churn", "Engagement (minutes/sessions)", "ARPU", "Ad yield", "Reactivation rate"],
    commonProblems: ["Serial churners", "Content-driven churn spikes", "Low engagement after trial", "Ad revenue decline"],
    drivers: ["Content slate", "Price / plan mix", "Personalised discovery", "Habit formation", "Bundles and partnerships"],
    martechStack: ["Subscription billing", "Product analytics", "CDP", "Engagement platform", "Recommendation engine", "Ad server"],
    channels: ["In-app", "Push", "Email", "Paid social", "Partnerships / bundles", "SEO"],
    economicModel: "Value = subscribers × ARPU × tenure (+ ad revenue per engaged user).",
    frameworks: ["cohort", "churn", "engagement-decay", "winback", "activation", "content-strategy"],
    benchmarkGuidance: "Compare churn by acquisition offer and content-entry title; engagement in first 14 days predicts retention.",
  },
  {
    id: "cpg",
    name: "Consumer Goods (CPG / FMCG)",
    businessModels: ["B2B2C (retail)", "D2C", "Quick commerce / marketplaces"],
    lifecycle: ["Awareness", "Consideration", "Trial", "Repeat", "Habit", "Advocacy"],
    kpis: ["Penetration", "Purchase frequency", "Market share", "Share of voice", "Trade promotion ROI", "Distribution / numeric reach", "D2C repeat rate"],
    commonProblems: ["Penetration decline", "Trade spend inefficiency", "Private-label pressure", "Weak first-party data", "Media ROI uncertainty"],
    drivers: ["Mental and physical availability", "Price / promotion", "Distinctive assets", "Innovation", "Retail execution"],
    martechStack: ["Retail media", "Data clean room", "CDP", "MMM", "Social listening", "D2C commerce"],
    channels: ["TV / CTV", "Retail media", "Paid social", "Influencers", "In-store", "Quick commerce"],
    economicModel: "Value = penetration × frequency × price × margin − trade and media spend.",
    frameworks: ["brand-funnel", "share-of-voice", "mmm", "price-elasticity", "creative-testing", "stp"],
    benchmarkGuidance: "Growth usually comes from penetration (more buyers) rather than loyalty; check panel data before targeting heavy buyers.",
  },
  {
    id: "qsr",
    name: "Restaurants & QSR",
    businessModels: ["B2C", "Franchise", "Delivery / aggregator", "Loyalty app"],
    lifecycle: ["Awareness", "First visit / order", "Repeat", "App adoption", "Loyalty", "Advocacy"],
    kpis: ["Same-store sales", "Visit frequency", "Average check", "App / digital mix", "Loyalty member share", "Aggregator commission share"],
    commonProblems: ["Aggregator dependency", "Declining visit frequency", "Discount fatigue", "Low app adoption"],
    drivers: ["Value / price", "Convenience", "Menu innovation", "Speed of service", "Offers and rewards"],
    martechStack: ["POS", "Loyalty platform", "Ordering app", "CDP", "Marketing automation", "Location analytics"],
    channels: ["App push", "SMS", "Aggregators", "Paid social", "Local search", "In-store"],
    economicModel: "Value = guests × frequency × average check × margin − delivery commission.",
    frameworks: ["rfm", "frequency", "loyalty-tiering", "app-growth", "price-elasticity", "winback"],
    benchmarkGuidance: "Compare frequency by daypart and channel; net out aggregator commission from digital sales.",
  },
  {
    id: "gaming",
    name: "Gaming",
    businessModels: ["Free-to-play", "Premium", "Subscription", "Ad-supported"],
    lifecycle: ["Install", "Tutorial", "D1 retention", "First purchase", "Engaged player", "Payer / whale", "Lapse", "Reactivation"],
    kpis: ["D1/D7/D30 retention", "ARPDAU", "Payer conversion", "CPI", "ROAS by cohort day", "LTV"],
    commonProblems: ["Rising CPI", "Early retention drop", "Low payer conversion", "Signal loss after ATT"],
    drivers: ["Core loop quality", "Live-ops events", "Monetisation design", "Social features", "Creative performance"],
    martechStack: ["MMP", "Product analytics", "LiveOps platform", "Ad mediation", "Engagement platform"],
    channels: ["App stores", "Paid UA networks", "Push", "In-game messaging", "Influencers / streamers", "Community"],
    economicModel: "Value = installs × retention curve × ARPDAU − CPI; payback day is the key constraint.",
    frameworks: ["app-growth", "cohort", "creative-testing", "paid-efficiency", "signal-loss", "engagement-decay"],
    benchmarkGuidance: "Compare cohort ROAS at D7/D30 by network and creative; never judge UA by installs alone.",
  },
  {
    id: "b2b_services",
    name: "B2B Services & Manufacturing",
    businessModels: ["B2B", "Sales-led", "Distributor / channel", "Contract / account-based"],
    lifecycle: ["Awareness", "Lead", "MQL", "SQL", "Opportunity", "Closed won", "Onboarding", "Expansion", "Renewal"],
    kpis: ["Pipeline coverage", "MQL→SQL rate", "Win rate", "Sales cycle length", "CAC", "Net revenue retention", "Share of wallet"],
    commonProblems: ["Low pipeline quality", "Sales–marketing misalignment", "Long cycles", "Weak account penetration", "Distributor data gaps"],
    drivers: ["Value proposition clarity", "Relationship strength", "Buying-committee coverage", "Pricing", "Proof / case studies"],
    martechStack: ["CRM", "Marketing automation", "ABM platform", "Intent data", "Sales engagement", "BI"],
    channels: ["LinkedIn", "Events / trade shows", "Content / SEO", "Sales outreach", "Partners", "Webinars"],
    economicModel: "Value = accounts × deal size × win rate × retention; pipeline velocity governs growth.",
    frameworks: ["b2b-funnel", "lead-scoring", "abm", "competitive", "value-based-pricing", "clv"],
    benchmarkGuidance: "Measure conversion by stage and source over a full sales cycle; avoid judging campaigns on MQL volume.",
  },
  {
    id: "other",
    name: "Other / General",
    businessModels: ["B2B", "B2C", "B2B2C", "Marketplace", "Subscription", "Transaction"],
    lifecycle: ["Awareness", "Consideration", "Purchase", "Onboarding", "Usage", "Repeat", "Loyalty", "Advocacy"],
    kpis: ["Revenue", "Active customers", "Retention rate", "Conversion rate", "CAC", "LTV"],
    commonProblems: ["Retention decline", "Acquisition efficiency", "Conversion decline"],
    drivers: ["Price", "Product", "Experience", "Relevance of communication", "Competition"],
    martechStack: ["CRM", "Marketing automation", "Analytics", "CDP"],
    channels: ["Email", "SMS", "Paid media", "Website", "Sales"],
    economicModel: "Value = customers × frequency × value × margin.",
    frameworks: ["funnel", "cohort", "lifecycle"],
    benchmarkGuidance: "Start with internal trend and cohort comparisons.",
  },
];

export const INDUSTRY_OPTIONS = INDUSTRIES.map((i) => i.name);

export function getIndustry(id: string | undefined): IndustryProfile | undefined {
  return INDUSTRIES.find((i) => i.id === id);
}

export function industryIdFromName(name: string): string | undefined {
  const n = name.trim().toLowerCase();
  const exact = INDUSTRIES.find((i) => i.name.toLowerCase() === n || i.id === n);
  if (exact) return exact.id;
  const aliases: Record<string, string[]> = {
    airline: ["airline", "aviation", "air travel", "carrier", "flight"],
    banking: ["bank", "fintech", "lending", "credit card"],
    insurance: ["insur"],
    retail: ["retail", "grocery", "fashion", "store"],
    ecommerce: ["e-commerce", "ecommerce", "online store", "d2c", "dtc", "marketplace"],
    hospitality: ["hotel", "hospitality", "resort"],
    telecom: ["telecom", "telco", "mobile operator", "broadband"],
    saas: ["saas", "software", "subscription software"],
    automotive: ["automotive", "automobile", "cars", "car maker", "vehicle", "dealership", "motors", "oem"],
    travel: ["travel", "otas", "ota", "tour operator", "tourism", "holiday"],
    healthcare: ["healthcare", "health care", "pharma", "hospital", "clinic", "medical", "patient", "diagnostics"],
    education: ["educat", "edtech", "school", "university", "college", "online course", "e-learning"],
    real_estate: ["real estate", "property", "proptech", "housing", "realty"],
    media: ["streaming", "publisher", "publishing", "newspaper", "ott", "music", "media company", "broadcast"],
    cpg: ["cpg", "fmcg", "consumer goods", "packaged", "beverage", "beauty", "cosmetic"],
    qsr: ["restaurant", "qsr", "food delivery", "cafe", "dining"],
    gaming: ["gaming", "mobile game", "video game", "esports"],
    b2b_services: ["b2b", "manufactur", "industrial", "professional services", "consulting", "logistics"],
  };
  for (const [id, words] of Object.entries(aliases)) {
    if (words.some((w) => new RegExp(`\\b${w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`).test(n))) return id;
  }
  return undefined;
}
