"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { BookOpenCheck, Compass, ExternalLink, KeyRound, Lightbulb, ShieldCheck, X } from "lucide-react";
import { PROVIDER_KINDS, PROVIDER_LABELS, type ProviderKind } from "@/ai/types";
import { Badge } from "@/components/ui";
import { cn } from "@/lib/cn";

/**
 * "Where do I get a key?" — step-by-step instructions per provider, opened
 * from an icon button next to the API key field. Plain guidance only: no
 * prices, which change often and differ by account.
 */

interface Guide {
  site: string;
  url: string;
  bestFor: string;
  steps: string[];
  format: string;
  notes: string[];
}

export const KEY_GUIDES: Record<ProviderKind, Guide> = {
  openrouter: {
    site: "openrouter.ai",
    url: "https://openrouter.ai/keys",
    bestFor: "One key for models from OpenAI, Anthropic, Google and others. Easy to switch models later.",
    steps: [
      "Go to openrouter.ai and sign in (Google, GitHub or email).",
      "Open Credits and add credits. A few models are free but have tight rate limits.",
      "Open Keys and click Create Key. Give it a name such as “GrowthPilot”; optionally set a credit limit.",
      "Copy the key straight away: it is only shown once.",
      "Paste it here. The model IDs are already filled in; browse others at openrouter.ai/models.",
    ],
    format: "Starts with sk-or-",
    notes: ["Set a credit limit on the key so spend can never surprise you."],
  },
  openai: {
    site: "platform.openai.com",
    url: "https://platform.openai.com/api-keys",
    bestFor: "GPT models directly from OpenAI.",
    steps: [
      "Go to platform.openai.com and sign in. This is the developer platform, separate from a ChatGPT subscription.",
      "Open Settings → Billing and add a payment method or prepaid credits. Keys without billing return quota errors.",
      "Open API keys and click Create new secret key. Choose the project and give it a name.",
      "Copy the key straight away: it is only shown once.",
      "Paste it here and click Test connection.",
    ],
    format: "Starts with sk-",
    notes: ["A ChatGPT Plus or Team plan does not include API access; API usage is billed separately.", "Set a monthly budget under Settings → Limits."],
  },
  anthropic: {
    site: "console.anthropic.com",
    url: "https://console.anthropic.com/settings/keys",
    bestFor: "Claude models directly from Anthropic. Strong at long, careful analysis and writing.",
    steps: [
      "Go to console.anthropic.com and sign in or create an account.",
      "Open Settings → Billing and buy credits.",
      "Open Settings → API keys and click Create Key. Give it a name such as “GrowthPilot”.",
      "Copy the key straight away: it is only shown once.",
      "Paste it here and click Test connection.",
    ],
    format: "Starts with sk-ant-",
    notes: ["A Claude.ai Pro or Team plan does not include API access; API usage is billed separately.", "Spend limits are set per workspace in the console."],
  },
  gemini: {
    site: "aistudio.google.com",
    url: "https://aistudio.google.com/apikey",
    bestFor: "Gemini models from Google. Google AI Studio has a free tier, which is handy for trying the product.",
    steps: [
      "Go to aistudio.google.com and sign in with a Google account.",
      "Open Get API key (left menu) and click Create API key.",
      "Pick an existing Google Cloud project or let AI Studio create one.",
      "Copy the key and paste it here.",
      "For higher limits, enable billing on the project from the same page.",
    ],
    format: "A long string generated by AI Studio",
    notes: ["On the free tier, Google may use prompts to improve its products and rate limits are low; for client work, enable billing.", "If a key leaks, delete it in AI Studio and create a new one."],
  },
  custom: {
    site: "your provider",
    url: "",
    bestFor: "Any OpenAI-compatible endpoint: Azure OpenAI, Groq, Together, Fireworks, DeepSeek, Mistral or your own gateway.",
    steps: [
      "In your provider's console, create an API key.",
      "Find the OpenAI-compatible base URL. It usually ends in /v1 (for example https://api.groq.com/openai/v1).",
      "Find the exact model names your account can use and enter them under Pick models.",
      "Paste the key and base URL here and click Test connection.",
    ],
    format: "Depends on the provider",
    notes: [
      "The endpoint must be reachable from where GrowthPilot is hosted: a model on your own laptop (localhost) cannot be reached by a cloud deployment.",
      "Screenshot reviews need a model that can read images.",
    ],
  },
};

export function KeyGuideButton({ kind, className }: { kind: ProviderKind; className?: string }) {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className={cn("inline-flex items-center gap-1.5 rounded-full border border-brand-600/20 bg-brand-50 px-2.5 py-1 text-xs font-medium text-brand-700 transition hover:bg-brand-100", className)}
      >
        <BookOpenCheck className="h-3.5 w-3.5" /> Where do I get a key?
      </button>
      {open && <KeyGuide initial={kind} onClose={() => setOpen(false)} />}
    </>
  );
}

export function KeyGuide({ initial, onClose }: { initial: ProviderKind; onClose: () => void }) {
  const [kind, setKind] = useState<ProviderKind>(initial);
  const g = KEY_GUIDES[kind];

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    document.addEventListener("keydown", onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose]);

  return createPortal(
    <div className="fixed inset-0 z-[70]" role="dialog" aria-modal="true" aria-label="Where to get an API key">
      <div className="absolute inset-0 animate-fade-in bg-slate-950/40 backdrop-blur-[2px]" onClick={onClose} />
      <div className="absolute inset-y-0 right-0 flex w-full max-w-xl animate-slide-up flex-col bg-canvas shadow-pop">
        <header className="flex items-start gap-3 border-b border-line bg-white px-5 py-4 sm:px-6">
          <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-brand-500 to-violet-500 text-white"><KeyRound className="h-5 w-5" /></span>
          <div className="min-w-0 flex-1">
            <div className="text-xs font-semibold uppercase tracking-[0.12em] text-brand-600">Setup guide</div>
            <h2 className="text-lg font-semibold tracking-tight">Where to get an API key</h2>
          </div>
          <button aria-label="Close guide" onClick={onClose} className="rounded-lg p-2 text-muted hover:bg-canvas hover:text-ink"><X className="h-5 w-5" /></button>
        </header>

        <nav aria-label="Providers" className="flex gap-1 overflow-x-auto border-b border-line bg-white px-5 py-2 sm:px-6">
          {PROVIDER_KINDS.map((k) => (
            <button
              key={k}
              type="button"
              aria-pressed={k === kind}
              onClick={() => setKind(k)}
              className={cn("shrink-0 rounded-full px-3 py-1 text-xs font-medium transition", k === kind ? "bg-brand-600 text-white" : "text-muted hover:bg-brand-50 hover:text-brand-700")}
            >
              {PROVIDER_LABELS[k].replace(" (OpenAI-compatible)", "")}
            </button>
          ))}
        </nav>

        <div className="flex-1 space-y-6 overflow-y-auto px-5 py-6 sm:px-6">
          <div className="rounded-xl border border-brand-600/15 bg-brand-50/60 px-4 py-3 text-sm">
            <span className="font-semibold text-brand-700">Good for: </span>{g.bestFor}
          </div>

          <section>
            <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold"><Compass className="h-4 w-4 text-brand-600" /> Steps</h3>
            <ol className="space-y-3">
              {g.steps.map((s, i) => (
                <li key={i} className="flex gap-3 text-sm">
                  <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-ink text-[11px] font-semibold text-white">{i + 1}</span>
                  <span className="leading-relaxed">{s}</span>
                </li>
              ))}
            </ol>
            <div className="mt-4 flex flex-wrap items-center gap-2">
              {g.url && (
                <a href={g.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-lg bg-brand-600 px-3 py-2 text-sm font-medium text-white hover:bg-brand-700">
                  Open {g.site} <ExternalLink className="h-3.5 w-3.5" />
                </a>
              )}
              <Badge>Key format: {g.format}</Badge>
            </div>
          </section>

          {g.notes.length > 0 && (
            <section>
              <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold"><Lightbulb className="h-4 w-4 text-amber-500" /> Good to know</h3>
              <ul className="space-y-2 text-sm">
                {g.notes.map((n, i) => <li key={i} className="rounded-lg border border-line bg-white px-3 py-2">{n}</li>)}
              </ul>
            </section>
          )}

          <section className="rounded-xl border border-emerald-200 bg-emerald-50/70 px-4 py-3 text-sm text-emerald-950">
            <h3 className="mb-1.5 flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-emerald-600" /> Keeping your key safe</h3>
            <ul className="list-disc space-y-1 pl-5">
              <li>GrowthPilot encrypts the key and never shows it again; only the last characters are displayed.</li>
              <li>Create a separate key just for GrowthPilot, so you can revoke it without affecting anything else.</li>
              <li>Never paste keys into chats, emails or documents. If one is exposed, revoke it in the provider console and create a new one.</li>
              <li>Customer personal data is masked before anything is sent to the provider.</li>
            </ul>
          </section>

          <section className="text-sm text-muted">
            <span className="font-medium text-ink">Not sure which to pick? </span>
            OpenRouter is the simplest start (one key, many models). Google Gemini has a free tier for trying things out. You can add several providers later; GrowthPilot falls back to the next one if one fails.
          </section>
        </div>
      </div>
    </div>,
    document.body,
  );
}
